### ISSUE TITLE
Infrastructure layer

### ISSUE THREAD

**Issue by alexsandro-xpt** [dotnet-architecture/eShopOnWeb#1]
Is this https://github.com/dotnet/eShopOnWeb/tree/master/src/Web/Infrastructure won't be at in Infrastructure project?

**Comment by ardalis** [comment]
I don't understand your question, sorry.

**Comment by CESARDELATORRE** [comment]
I think he's saying if you're going to move the Infrastructure folder within the Web app to the Infrastructure project.


________________________________

**Comment by alexsandro-xpt** [comment]
Exactly @CESARDELATORRE it's probability should be move for Infrastructure project.

**Comment by ardalis** [comment]
Yes, that's ultimately the plan. I started down that path but the current codebase doesn't really have enough functionality to merit it. Time permitting, I will expand the scope of the demo and you'll see that happen, hopefully in the very near future.

**Comment by Ibrahim-Islam** [comment]
Why is it called "Infrastructure"? Shouldn't "DAL" or "Data" be more appropriate?

**Comment by chriswoodward** [comment]
Further to this, what I don't understand is if the eShopOnWeb application is meant to support the "Architecting and Developing Modern Web Applications with ASP.NET Core and Azure" eBook (as claimed) then why is the EntityFramework CatalogContext class located in the Web UI Project ?

**Comment by ardalis** [comment]
It's incomplete as yet. The goal is to mimic (some of) the functionality of the eShopOnContainers sample. I'm actively working on it.

**Comment by ardalis** [comment]
Closing this since the Infrastructure folder in the Web project has been removed and all of its contents now reside in the Infrastructure project.
