### ISSUE TITLE
Verify devcontainer for codespaces debugging

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-architecture/eShopOnWeb#1003]
Verify that you can create a new GitHub Codespace for this repo, spin up all the services, ports get forwarded, and everything works. Modify the .devcontainer file if necessary.

**Comment by SrushtiPasari94** [comment]
@jamesmontemagno 
Can you please Add description for this task.

**Comment by jamesmontemagno** [comment]
done

**Comment by SrushtiPasari94** [comment]
Verified [ vs-code-dev-containers ](https://github.com/SrushtiPasari94/eShopOnWeb/blob/main/.devcontainer/devcontainerreadme.md#vs-code-dev-containers) . Working fine. Able to load site.

For new GitHub Codespace , getting one issue. Working on it. rest issues are resolved.

**Comment by SrushtiPasari94** [comment]
Working fine by:
1. Adding **"UseOnlyInMemoryDatabase": true,** in appsettings.json
2. Making Port Protocol Https.
![image](https://github.com/dotnet-architecture/eShopOnWeb/assets/136682990/b1e63f92-310a-4332-89cb-46401b5d2e19)

**Comment by jamesmontemagno** [comment]
Lovely! can we document that @SrushtiPasari94

**Comment by SrushtiPasari94** [comment]
@jamesmontemagno  
Its already documented in [Tips section](https://github.com/SrushtiPasari94/eShopOnWeb/blob/main/.devcontainer/devcontainerreadme.md#tips-and-tricks)

If required I can add image to make the second tip about port forwarding more understandable. 
Please let me know if it's needed.
