### ISSUE TITLE
Namespaces need standardization

### ISSUE THREAD

**Issue by hutchcodes** [dotnet-architecture/eShopOnWeb#101]
In the ApplicationCore project some of the classes are defined in the `ApplicationCore.*` namespace, some are defined in `Microsoft.eShopWeb.ApplicationCore.*` namespace. The default namespace is `ApplicationCore`

Similar issue in the Web project where most of the project is under `Microsoft.eShopWeb.*`, but a few classes have been created in `Web.*` which is the default namespace.

As someone who is reading through this trying to my bearings it would be helpful if this were standardized in some way. Either all namespaces starting with `Microsoft.eShopWeb` or just `eShopWeb` or even no global name space and each project starts it's namespacing with it's project name.

I'll be standardizing for myself, and would be happy to submit a PR for whatever direction the maintainers think makes the most sense.

**Comment by ardalis** [comment]
Agreed this should be fixed. I can get to it this week but would take a PR if you want to knock it hit sooner. I would standardize in the Microsoft.eShopWeb prefix and make that the project default as well.
