### ISSUE TITLE
Pagination not being reset

### ISSUE THREAD

**Issue by samsar777** [dotnet-architecture/eShopOnWeb#104]
Once being on the page number 2 you change filters, after refresh page is still set to 2. Thus there are no results as filtered products fit on one page entirely.

Same clicking on the logo shall return current page to 1 (although can keep value of selected filters - it works this way now).
 
I have tried to change it on my own, however this is just the beginning of journey with Asp.net. Too early on my learning curve.

**Comment by ardalis** [comment]
When I click on the link to go to page 2, then change the filter (e.g. to choose Mugs) and then click the button next to the filter, I'm taken to a page showing 2 of 2 mugs (page 1). I'm not able to reproduce the issue you're describing.

**Comment by samsar777** [comment]
Herewith steps to reproduce

1. Open app in initial state Brand=All, Type=All, Page=1 of 2)
2. Change page to 2. Only two items shall be visible.
3. Change Type to Mug, press button
4. No items displayed "THERE ARE NO RESULTS THAT MATCH YOUR SEARCH" nor pagination controls. Seems app is set to page 2 which does not exist with given filters.

However is is not true, because thare are two Mugs. To see them, show all items again, go back to page 1, change Type to Mug.

I am using release named netcore2.1 (8bf2a7a).
![screenshot](https://user-images.githubusercontent.com/15112811/41283135-15f37232-6e36-11e8-8cb4-ada0835cbaef.png)

**Comment by ardalis** [comment]
Ah, I was able to reproduce it, but only for the WebRazorPages project, not the Web project.

**Comment by samsar777** [comment]
Sorry that I didn't report it properly.

**Comment by ardalis** [comment]
No worries, I appreciate you reporting it at all! :)
