### ISSUE TITLE
When to use service or repository 

### ISSUE THREAD

**Issue by chamikasandamal** [dotnet-architecture/eShopOnWeb#105]
`IOrderRepository` is used in `OrderController` and `IOrderService` is used in `BasketController` 
Why you are not using `IOrderService` in both of the locations?

**Comment by ardalis** [comment]
`IOrderService` exists to coordinate between `Basket`, `Order`, and `CatalogItem`. It only has one method, `CreateOrderAsync`, for this purpose. `BasketController` needs this method, so it uses `IOrderService`.

`IOrderRepository` has methods for fetching `Order` entities from persistence. `OrderController` needs these methods, so it uses this repository. If creating an `Order` was a simple `.Add(new Order())` approach, I wouldn't have used a service for it and both places would just use the repository.

On a related design note, I tried to keep controllers (and other clients of dependencies) at a common level of abstraction with regard to their dependencies. That means, if the controller is working with repositories, it stays at that level (and doesn't take a dependency on a service). If the controller is working with services, it doesn't also pull in repositories. At least in the case of `BasketController` and `OrderController` you can see I'm following this guidance.
