### ISSUE TITLE
insert and update date

### ISSUE THREAD

**Issue by farhad2161** [dotnet-architecture/eShopOnWeb#107]
I have insert date and update date fields in all of my tables. Where is the best place to set this fields automatically?

**Comment by ardalis** [comment]
Best is a matter of taste, I suspect. The simplest approach is probably to just use triggers (and/or default values for the insert date) in the database to set these. Given that you have them on "all of your tables" it sounds to me like a cross-cutting concern that can remain in the data/database layer.

If triggers don't work, then my next recommendation would be to do it in the ORM, by modifying your DbContext to do the work. This should minimize the amount of duplicate code you have in your domain model (and this doesn't sound like business logic that belongs in the domain model).

If neither of the above work, you could resort to doing the work in the entities themselves, but that seems most prone to error and will clutter the entities with extra code and responsibilities.
