### ISSUE TITLE
"Send Email Verification" doesn't work

### ISSUE THREAD

**Issue by deepfamous** [dotnet-architecture/eShopOnWeb#108]
Clicking "Send Email Verification" results in EmailConfirmationLink returning a null value for me. Any Ideas how to fix it?

**Comment by somecodestuff** [comment]
Assuming you're running the WebRazorPages project, the error occurs because Pages/Account/ConfirmEmail.cshtml is missing. Add that page back in (you can get it from the Razor Pages template project) and it should work.
