### ISSUE TITLE
How to migrate a database

### ISSUE THREAD

**Issue by ggSui** [dotnet-architecture/eShopOnWeb#11]
More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands. 
I dot't know

**Comment by ardalis** [comment]
These two commands from the Web folder should produce the migrations for the catalog:

```
dotnet restore
dotnet ef database update --context Microsoft.eShopWeb.Infrastructure.CatalogContext
```

The authentication migrations are not yet in the project. Once they are, you would change the context name to the fully qualified name of the AppIdentityDbContext class.
