### ISSUE TITLE
Question: Why await inside the repository?

### ISSUE THREAD

**Issue by eluchsinger** [dotnet-architecture/eShopOnWeb#111]
Why do you have to `await` inside the repository? Couldn't you just return the task?
[Example code](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/EfRepository.cs#L37)

**Comment by ardalis** [comment]
I think we could just return the task. I'll make an update unless you want to do a quick PR?

**Comment by eluchsinger** [comment]
I can make a PR later today.

**Comment by KhalilMohammad** [comment]
What is the reasoning behind removing await keyword?

**Comment by valdirviana** [comment]
The reason because have `await` is the point to access IO via _dbContext async methods. Removing the `await` the method of the repository will lost your async feature.

**Comment by ardalis** [comment]
Based on the docs (and summed up here: https://stackoverflow.com/a/43497310/13729 ) I believe having the `await` within each repository method is appropriate, as it ensures no client of the repository will fire off multiple tasks in parallel.

**Comment by eluchsinger** [comment]
@KhalilMohammad I am not sure what anti-pattern you're talking about. I see at least two issues here.

The point of removing the `await` keyboard was to avoid an unnecessary context switch inside the method* (1st issue). But as @ardalis  said, EF does not support two parallel operations so it is appropriate to utilize an `await` inside the method (2nd issue).

##### * More explanation

What happens when you `await`? The execution of the asynchronous code happens in a new thread (let's say Thread 2). When the asynchronous work is done, the further execution of the code will happen again in the originally executing thread (let's say Thread 1). This causes a possibly unnecessary context switch between these threads. Usually, you don't need to proceed executing the code after the `await` in Thread 1 (except we're talking about a UI / Main Thread).
