### ISSUE TITLE
Question: Why interfaces are in Web not in ApplicationCore

### ISSUE THREAD

**Issue by iamsky13** [dotnet-architecture/eShopOnWeb#115]
Why ICatalogService and IBasketViewModel are at Web not in ApplicationCore?

**Comment by fabercs** [comment]
@iamsky13 the answer is given [here](https://github.com/dotnet-architecture/eShopOnWeb/blob/1b5b179c7f55b9b032695b26115ae8ddb6faae3c/src/Web/Services/CatalogService.cs#L15)
