### ISSUE TITLE
what is the db design

### ISSUE THREAD

**Issue by yhzjut** [dotnet-architecture/eShopOnWeb#116]
for example order table design，orderitem tabledesign？

**Comment by ardalis** [comment]
They are created using EF migrations. You can see the scripts in the Infrastructure/Data/Migrations folder. The sample is often run with just the InMemory provider, so the database design isn't relevant. However,  you can use it with a database - here's a screenshot:

![image](https://user-images.githubusercontent.com/782127/42816443-d213a39c-8998-11e8-9366-7ed81acb32f3.png)

...which reminds me, we should put some constraints on the string types to specify their maximum sizes. I'll create a separate issue for that.
