### ISSUE TITLE
Constrain String Property Max Length in Database

### ISSUE THREAD

**Issue by ardalis** [dotnet-architecture/eShopOnWeb#117]
Currently all string properties are nvarchar(max) in the db schema. Add max length and any other reasonable constraints using fluent syntax.

**Comment by kdcllc** [comment]
To have Fluent Api or attribute based restriction?

**Comment by ardalis** [comment]
" using fluent syntax." please.

**Comment by vertonghenb** [comment]
Agreed!

We should even create separate ConfigurationFiles based on IEntityTypeConfiguration<T> for each Entity.

E.g. OrderConfiguration in the ...Data.Configurations namespace
