### ISSUE TITLE
Usage of areas

### ISSUE THREAD

**Issue by btastic** [dotnet-architecture/eShopOnWeb#118]
Hey there,

I always like to take a look at this project for some inspiration on how to solve some stuff. Right now I have the problem that I want to use the areas feature, but I don't know how to apply it correctly.

I have something like this:

- Areas
  - Cart
    - Cart.cshtml
  - Product
    - Products.cshtml
    - Product.cshtml

Now to link to either page I do something like this:

`<a asp-area="Product" asp-page="Products"></a>`
`<a asp-area="Cart" asp-page="Cart"></a>`

But the url will be `localhost:5001/products/products` but I want it to be `localhost:5001/products`. How would I approach this?

If this is the wrong repo, just guide me to the right one. Would be happy to get some help on this one, as seemingly nobody uses it. Everyone just tosses the pages in the default pages directory.

**Comment by efleming18** [comment]
Hi @btastic just following up here. Do you still need some guidance? I'm sure you've checked out [the Docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.2) on Areas in .NET Core. That provides some pretty useful information. Do you have a repo or anything as an example I could maybe take a look at?

This might not be the best repo for your question as we don't use Areas, but if you have an example repo for me to play around with I will do my best to come up with something for you!

@ardalis may know of another repo off the top of his head that utilizes Areas though.

**Comment by btastic** [comment]
Hey @efleming18,

thank you for following up. We went with something different, but I would still like to know how to achieve something I described via Areas. So I don't have a need for it right now, but I'd still love to see a sample that uses it. Maybe @ardalis knows something, like you already asked.

Thank you!

**Comment by ardalis** [comment]
Why wouldn't you name your area `products` and make the root page just HomeController + Index.cshtml? Same for Cart. There's no need to repeat the name of the area:
/Areas/Products
       HomeController.cs
      Views
           Home
                 Index.cshtml
/Areas/Cart
       HomeController.cs
      Views
           Home
                 Index.cshtml

Personally that seems like a lot of files and folders for 2 views but I'll assume that in your actual project you have more stuff going on. You should also check out [Feature Slices](https://ardalis.com/msdn-feature-slices-for-aspnet-core-mvc) and of course then my [Razor Pages article](https://ardalis.com/aspnet-core-razor-pages-worth-checking-out) and [associated repo](https://github.com/ardalis/OrganizingAspNetCore).

Closing but feel free to comment further if you have more questions.
