### ISSUE TITLE
Docker Issue running from Dockerfile's, not docker-compose.

### ISSUE THREAD

**Issue by michael-nee** [dotnet-architecture/eShopOnWeb#121]
When I use to run from the dockerfile build's I get errors regarding DbContext.

> No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

Everything works when I startup using docker-compose build and then docker-compose up.

**Comment by CESARDELATORRE** [comment]
Not sure if I understood your question.
Basically, if you just run the app's container with "docker run" (is that what you mean), there's no SQL database container running, you are starting just the web app's container, therefore, you get the errors.

With docker-compose you can set dependencies between containers, so if the web app depends on the SQL container, this will also be started even if you are just starting the web app container explicitly with docker-compose.
IF you simply use "docker-compose" it will start all the containers specified in the docker-compose.yml file which includes the SQL container.

**Comment by michael-nee** [comment]
Docker-Compose doesn't run an SQL Container.  It just starts both MVC and RazorPages containers from their images.

**Comment by michael-nee** [comment]
Found the issue.

The original docker files has setting the environment variable to Development commented out, while Docker Compose has it as an command to pass in.

**Comment by ardalis** [comment]
Ah, that would do it, thanks. Without that variable, the containerized app will look for a database that isn't present. Do you want to send a small PR, or just let me fix it?

**Comment by michael-nee** [comment]
Happy for you to do it.  Also for the MVC Web app, the run command port mapping isn't 1 to 1

> docker run --name eshopweb --rm -it -p 8000:5106 web

Should ideally be 5106:5106.

**Comment by kdcllc** [comment]
@ardalis, I have feature PR with Docker files fixes and db fluent syntax added.

**Comment by efleming18** [comment]
Closing this issues as https://github.com/dotnet-architecture/eShopOnWeb/pull/120 has been closed and the docker issues seem to be resolved as updates have come in.
