### ISSUE TITLE
Question: Should the same dbContext be used within each EfRepository?

### ISSUE THREAD

**Issue by politigf** [dotnet-architecture/eShopOnWeb#122]
I have based parts my project on the eShopOnWeb solution, and I recently ran into what looks like a race condition due to the same dbContext being used in multiple repositories. I re-visited the eShopOnWeb solution and added a simple Guid property to the CatalogContext that gets set in the constructor. Then, when I set a breakpoint and debug the solution.

In this code:

`        public CatalogService(
ILoggerFactory loggerFactory,  
            IRepository<CatalogItem> itemRepository,  
            IAsyncRepository<CatalogBrand> brandRepository,  
            IAsyncRepository<CatalogType> typeRepository,  
            IUriComposer uriComposer)  
        {
            _logger = loggerFactory.CreateLogger<CatalogService>();
            _itemRepository = itemRepository;
            _brandRepository = brandRepository;
            _typeRepository = typeRepository;
            _uriComposer = uriComposer;
        }
`
Each of the repositories in that constructor are using the same CatalogContext instance.

The race condition in my code is within a service much like the catalog service above where a method is calling two async methods on two different IAsyncRepositories. I'm getting sporadic errors, sometimes the error is "The connection was not closed. The connection's current state is connecting”. Should the db context be shared among multiple repositories?

**Comment by politigf** [comment]
The services/repos are scoped, and I thought it should be fine too, however when I do something like the following:

`await Task.WhenAll(task1, task2, task3);`

and each of those tasks is a call into an async method within the same service, I'm hitting the race condition with sporadic different errors (but most often gets the error in my original post), because they're all using the same context and running in parallel. 

So, I did some more digging and answered my own question. **EF Core does not support multiple parallel operations being run on the same context instance**.

[Reference in ms docs](https://docs.microsoft.com/en-us/ef/core/querying/async)

Shame on me for trying to shave a few milliseconds off a request! ;)

**Comment by ardalis** [comment]
Glad to see this is sorted out. I'd like to be able to reproduce the issue, though, so I can document it better. Can you share more of your code, in terms of what the tasks are doing that's causing the problems? I tried putting together a very simple ASPNET Core app (separate from this repo) that did this inside a controller action, but I haven't gotten it to fail yet:

```
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public HomeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var task1 = _db.Artists
                .Include(a => a.Albums)
                .ThenInclude(a => a.Songs).ToListAsync();
            var task2 = _db.Artists
                .Include(a => a.Albums)
                .Where(a => a.Name.EndsWith('f'))
                .ToListAsync();
            var task3 = _db.Artists
                .Include(a => a.Albums)
                .Where(a => a.Name.EndsWith('1'))
                .ToListAsync();
            var task4 = _db.Artists
                .Include(a => a.Albums)
                .Where(a => a.Name.EndsWith('9'))
                .ToListAsync();


            var allresults = await Task.WhenAll(task1, task2, task3, task4);
            return View();
        }
```

**Comment by politigf** [comment]
I went back and reviewed the code from before I removed the Task.WhenAll, and the only real difference between what I had and yours was that each of the context calls where in methods that called a service and I was doing a Task.Delay(5000); in each just for testing which seemed to exacerbate the problem. It looked like this:


```
        private async Task SetupItemViewModel(ItemViewModel model)
        {
            var populateCountriesTask = PopulateCountriesList(model);
            var populateManufacturersTask = PopulateManufacturerList(model);

            await Task.WhenAll(populateCountriesTask, populateManufacturersTask);
        }

        private async Task PopulateCountriesList(ItemViewModel model)
        {
            await Task.Delay(5000);
            model.CountryList = await _itemService.GetCountries();
        }

        private async Task PopulateManufacturerList(ItemViewModel model)
        {
            await Task.Delay(5000);
            model.ManufacturerList = await _itemService.GetManufacturers();
        }
```
