### ISSUE TITLE
Replace Bower in Web and WebRazorPages

### ISSUE THREAD

**Issue by ardalis** [dotnet-architecture/eShopOnWeb#124]
Bower has been deprecated and is no longer used by ASP.NET Core project templates. See this related issue: 
https://github.com/dotnet-architecture/eShopOnContainers/issues/670

**Comment by CESARDELATORRE** [comment]
I thought you updated this as part of the last upgrade to ASP.NET Core 2.1.. since it should be aligned to the ASP.NET Core 2.1 templates.

**Comment by ardalis** [comment]
It's not being used but it looks like the files were left behind (bower.json, .bowerrc). Looking at the current 2.1 templates, there's no bower but also nothing else for client side package management. I'll simply remove the files for now and close this out.

**Comment by ardalis** [comment]
Fixed by https://github.com/dotnet-architecture/eShopOnWeb/commit/95a2a6208f915c92aa30dcef65edbd2ba9e60706
