### ISSUE TITLE
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (

### ISSUE THREAD

**Issue by levalencia** [dotnet-architecture/eShopOnWeb#13]
I have something weird after downloading, restoring and rebuilding I get this:

> Restoring NuGet packages...
> To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
> Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
> One or more packages are incompatible with .NETCoreApp,Version=v1.1.
> Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
> One or more packages are incompatible with .NETCoreApp,Version=v1.1.
> Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
> One or more packages are incompatible with .NETCoreApp,Version=v1.1.
> NuGet package restore failed

the weird thing is that even with the errors, it says build succeeded.

**Comment by ardalis** [comment]
This is likely related to this issue: https://github.com/dotnet/corefx/issues/18452

I'm fixing now by removing some packages.
