### ISSUE TITLE
Use Private Constructors and Setters in the domain

### ISSUE THREAD

**Issue by vertonghenb** [dotnet-architecture/eShopOnWeb#145]
As of EF Core 2.1 we can use Private Constructors/Setters to encapsulate the Domain.

EF used to break the encapsulation principal of the domain since we had to use Public Setters, but as of 2.1 we can use a real DDD approach again. I do believe we should promote this feature.

**Comment by michelcedric** [comment]
I made a Pull Request to put Setter as Private.
https://github.com/dotnet-architecture/eShopOnWeb/pull/349

**Comment by michelcedric** [comment]
The PR is accepted i think this one could be closed.

**Comment by efleming18** [comment]
Thanks, @michelcedric !
