### ISSUE TITLE
error NU1202: package Microsoft.CodeAnalysis.CSharp.Workspaces 2.8.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1)

### ISSUE THREAD

**Issue by ggros** [dotnet-architecture/eShopOnWeb#152]
Tried to build with VS 2017 15.8.7 (net core 2.1.5) and got error:
error NU1202: package Microsoft.CodeAnalysis.CSharp.Workspaces 2.8.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1)

Solved the issue removing the nuget package from Web.csproj Microsoft.VisualStudio.Web.CodeGeneration.Design Version="2.1.3"

**Comment by efleming18** [comment]
Closing this issue as we're now on 2.2 and package listed above does not appear to still be in the solution.
