### ISSUE TITLE
Validation in Setter instead of Constructor

### ISSUE THREAD

**Issue by vertonghenb** [dotnet-architecture/eShopOnWeb#157]
This issue builds further on the idea of: https://github.com/dotnet-architecture/eShopOnWeb/issues/145

Currently all the validation logic of the domain models are happening in the Constructor which is not always the best choice, since the properties are set via a private setter. This means we can still manipulate them in the domain entity itself, even if it's invalid.

Since EF Core 2.1 does't use the setter, but the backing field and not re-validating each time. We should move our Validation logic into the setter instead of the constructor. This makes sure the property and entity are never in  an invalid state. Altough this will create additional Fields.

An example: 
https://github.com/dotnet-architecture/eShopOnWeb/blob/156d5c6b25af87699ab7201edee440ec8ba2e643/src/ApplicationCore/Entities/OrderAggregate/Order.cs#L16

In Basket.cs, we're even using a public setter for the buyerId, without a constructor.
https://github.com/dotnet-architecture/eShopOnWeb/blob/156d5c6b25af87699ab7201edee440ec8ba2e643/src/ApplicationCore/Entities/BasketAggregate/Basket.cs#L9

**Comment by michelcedric** [comment]
Normaly tor a real DDD approach. All property should be Private. I create a pull request for that https://github.com/dotnet-architecture/eShopOnWeb/pull/349

**Comment by michelcedric** [comment]
The PR is accepted i think this one could be closed.

**Comment by efleming18** [comment]
Thanks, @michelcedric !
