### ISSUE TITLE
HashSet vs List in Navigation Collections

### ISSUE THREAD

**Issue by vertonghenb** [dotnet-architecture/eShopOnWeb#158]
Currently we expose a `IEnumerable<T>` for navigational collections, the backing collection is a `List<T>`. But isn't a backing `HashSet<T>` more performant?

Thoughts are welcome!

**Comment by BlackFrog1** [comment]
I don't know this code-base.  Can you provide example of where you are taking about in the code?  And possible some code where the `HashSet<T>` would be more performant.

**Comment by vertonghenb** [comment]
An example: https://github.com/dotnet-architecture/eShopOnWeb/blob/b123945a01b8c82dfbaea22fefc2a5c06ad8c263/src/ApplicationCore/Entities/BasketAggregate/Basket.cs#L11

**Comment by ardalis** [comment]
Do you have some example or reference link for this? For small result sets (everything in this application is fewer than 20 items) I don't imagine there is any performance difference to worry about.

**Comment by vertonghenb** [comment]
@ardalis indeed, the collections are rather small.
//Closing
