### ISSUE TITLE
When deployed on IIS, get error 404

### ISSUE THREAD

**Issue by yangxinyun** [dotnet-architecture/eShopOnWeb#162]
Need help here. After publishing the web MVC to  folder and created website based on the folder, the website cannot be visited with error 404.

**Comment by ardalis** [comment]
Go to the Web project folder in a console/terminal and run 'dotnet run'. Let me know if that works or what error you see.

**Comment by rjs123431** [comment]
If you are using IIS on local machine, make sure you have .net core runtime installed https://www.microsoft.com/net/download
and check application pool .NET CLR version should be 'No manage code'

**Comment by yangxinyun** [comment]
Hi , It is really specific issue to the eshop website. I can create and run a dummy asp.net core MVC and deploy it to local folder and run it without problem. But when it comes to the eshop,I can only run it within VS or change project debug setting to deploy it to IIS. But this is not the same type of deploy as you click publish in VS to folder

**Comment by yangxinyun** [comment]
Is there anyone who had successfully deployed the eShopOnweb site to IIS? Can u share with us your way of getting this done?

Thanks in advance

**Comment by rjs123431** [comment]
works for me. had to changed the connection strings to
```
"CatalogConnection": "Server=localhost;Initial Catalog=Microsoft.eShopOnWeb.CatalogDb;Integrated Security=False;User Id=[user];Password=[password];",
"IdentityConnection": "Server=localhost;Initial Catalog=Microsoft.eShopOnWeb.Identity;Integrated Security=False;User Id=[user];Password=[password];"
```
Modify that to your own credentials

I think the real issue here is that it can't connect to the database, and will try to render the /Catalog/Error but can't find it so it returns 404 instead

**Comment by yangxinyun** [comment]
Hi rjs123431,

Thank you for your reply. I suspect this in the beginning as well. However, to exclude this , I used inMemoryDB instead by configuring start.cs to use the InMemoryDB, it still failed with 404. But at this time, no error can be found in eventviewer.

Just to be crystal clean, did u publish it by issuing publish cmd from mvc project  context menu in VS and select publish to file system? and you manually create a website in IIS and set its applicationpool to use No Managed Code? Anything more or less?

Thank you

**Comment by rjs123431** [comment]
Yes, that's what I did. Clone this repo, modify the appsettings, right-click the **Web** project > Publish to folder `\eShopOnWeb\src\Web\bin\Debug\netcoreapp2.1\publish`, create website in in IIS and change application pool

**Comment by yangxinyun** [comment]
Thanks rjs123431 for your help. The problem is finally solved. The root cause is ,as you pointed out, with sql DB connection credential. I managed to make it work by using my identity as app pool identity. The detailed log can be enabled from web.config generated on deployment time which may be helpful for those who is incurring strange issue.

One more question for you rjs123431 if I may, your reasoning about why I ended up with a 404 makes sense to me. But it just couldn't be fixed by adding an error page under /Catalog/Error. Do u know why?

Thanks

**Comment by rjs123431** [comment]
Hi, glad you got it working.

About the 404, I suspect its because of the routing. No default template in `Startup.cs` `app.UseMvc()` and if you look at CatalogController there is `[Route("")]` and `[HttpGet("Error")]`. I don't have enough knowledge so I can't explain this. But you can easily fix that by either changing `Startup.cs` to `app.UseExceptionHandler("/Error");` or the `CatalogController` `[HttpGet("Catalog/Error")]`
