### ISSUE TITLE
User.Identity.IsAuthenticated is false after successful login

### ISSUE THREAD

**Issue by Balirezaei** [dotnet-architecture/eShopOnWeb#163]
Need help here.Context.User.Identity.IsAuthenticated is false after  successfull login ? I just run downloaded git code.

**Comment by Balirezaei** [comment]
I used Firefox and it worked :(

**Comment by ardalis** [comment]
Which browser did you use when it didn’t work?

**Comment by Balirezaei** [comment]
> Which browser did you use when it didn’t work?

Google Chorome

**Comment by ardalis** [comment]
Great! Not sure what the issue was - let me know if you see it again.
