### ISSUE TITLE
Where should i put AutoMapper ?

### ISSUE THREAD

**Issue by apincik** [dotnet-architecture/eShopOnWeb#165]
In case i have services, entites in Core and i have ViewModels in Web project.

Should i use automapper in controller and just passed mapped entity to service ?

What could be the cleanest solution. For example i need to update an entity, so i map viewmodel to entity in controller and i call service->update(int id, Entity entity). Or just set ID in controller and other stuff and just call service to update values.

Or possibility to divide services from Core to unique layer, add references or create Model (entites for viewmodel, for mapping..) in Infrastructure.

Thanks

**Comment by fiseni** [comment]
Hi,

Either way is correct. Everything is arbitrary and it depends on the scope of the project.
If you do the mappings in the controllers, that actually means that your UI layer is aware of your domain model. That's totally OK for relatively small/medium projects. In case of larger projects, enterprise applications, then you might consider the following topics as a starting point
- Domain Services - These constructs will work with your domain model, and their main purpose is to mediate/orchestrate between different aggregate roots. If your intended actions doesn't encompass several aggregate roots, then keep it simple and access them directly, don't hide them behind a service.
- App Services - Actions defined here would return view models. They would utilize one or more domain services, would do the appropriate mappings and return a view model ready to be consumed from UI. For large projects, you may even want to keep them in a separate layer (e.g. Application layer), so all different kind of UI you might have (Web, WPF etc), would consume the same services.
- UI - In our case the controllers (easily can be some desktop app or whatever), has no knowledge of the domain model and works only with view models. All required actions are completed through defined app services.

It's important to emphasize that all these patterns/techniques are nothing else than just a "collective wisdom" of the community. With time we found working solutions for known problems. But, it's a common mistake to apply those solutions just for sake of applying them. In the end, you might not having those problems at all.
