### ISSUE TITLE
Missing preposition

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet-architecture/eShopOnWeb#180]
Hi Steve,

In chapter 7, page 58, first paragraph and first sentence, *Filters are usually implemented as attributes, so you can apply them controllers or actions.* should be  Filters are usually implemented as attributes, so you can apply them **on** controllers or actions.

Would you please fix it?

Thanks & Best Regards,
Maher

**Comment by ardalis** [comment]
Thanks, I'll get this fixed during my current editorial pass while updating for 2.2.

**Comment by MaherJendoubi** [comment]
@ardalis Excuse my ignorance about choosing the correct preposition but I felt that was something missing. Thank you for the correction.

**Comment by ardalis** [comment]
No, thank you for pointing it out. I just rephrased it slightly since I was already in there. :)
