### ISSUE TITLE
Question: Why ApplicationUser inside Infrastructure?

### ISSUE THREAD

**Issue by TheDayIsMyEnemy** [dotnet-architecture/eShopOnWeb#182]
Hello,
Isn't ApplicationUser part of the Core project?
Can you explain me please?

**Comment by TheDayIsMyEnemy** [comment]
Hi Steve, can you answer please?
In your books you say: "Business entities that need to be persisted are defined in the ApplicationCore "
What happens in case a business entity have a connection with the ApplicationUser?

**Comment by efleming18** [comment]
@ardalis Do you know the history on this one?

**Comment by hanshenp** [comment]
@efleming18 I am curious if you have any news on this one.

**Comment by ardalis** [comment]
Sorry I haven't answered this sooner. @yarrgh 's answer is correct, historically. It's also the case that ApplicationUser is not really a concern of the domain in this application. It's not used in any meaningful way, it has no behavior, and the only part of it that's needed is its ID or even just an email address. By keeping it out of the ApplicationCore its coupling to Identity is kept out as well, and it's easier to refactor the auth functionality of the app into a separate microservice if desired (see eShopOnContainers for an example of this). If it were refactored into a microservice, the only thing the store's domain model would need is, again, some kind of identifier (GUID or email address, for instance).

If you have an application that needs to have additional data and behavior about the current user, you can still follow this same approach. Keep the class used by your application's identity provider out of your domain model and just use its key as a key (primary or surrogate) on your domain's `User` or `Customer` or `Member` or whatever entity. Now your identity implementation details are decoupled from your domain model. You don't have to follow this approach, but I've used it successfully in many applications without significant downsides. Hope this helps.

**Comment by TheDayIsMyEnemy** [comment]
Hi and thank you for the answer.
If it's possible, could you give some small example about how to correctly implement the idea you gave.
Thanks! :)

**Comment by TheDayIsMyEnemy** [comment]
Do you mean to just keep the UserId without navigation property to User (cause it's not possible without reference to Infrastructure) and just use it like that? without any relationship between User and Customer in the db?

**Comment by ardalis** [comment]
Yes, exactly. There's technically nothing to prevent an invalid UserId string being assigned to `Customer` but that's what unit tests would help with. Keeping them less tightly coupled also allows the auth functionality to be move/replaced/modified as needed without impacting the domain. You can see an example of pulling auth completely out into a separate service in the eShopOnContainers solution.

**Comment by TheDayIsMyEnemy** [comment]
Okay thanks for the clarification :) I will look at eShopOnContainers solution.
