### ISSUE TITLE
Clean up web.csproj

### ISSUE THREAD

**Issue by ardalis** [dotnet-architecture/eShopOnWeb#186]
Figure out why it has so many files added using things like:
`UpToDateCheckInput`
and
`_ContentIncludedByDefault`

**Comment by efleming18** [comment]
I have not been able to find much information as to why these were added during the upgrade, other than one similar question that doesn't appear like it will get an answer. https://github.com/aspnet/Docs/issues/10917
I will cleanup the csproj file and keep an eye out for any other relevant information.
