### ISSUE TITLE
No idea how to start connection

### ISSUE THREAD

**Issue by schrodog** [dotnet-architecture/eShopOnWeb#199]
when I set `docker-compse up` successfully, it says
`Now listening on: http://[::]:80`, but I cannot access both in
localhost:5106 and [::]:80

**Comment by ardalis** [comment]
I changed the mapping in the docker-compose.yml file to map to 80 and it's working for me now - please confirm.

**Comment by efleming18** [comment]
@schrodog Have you been able to try it out yet?

**Comment by efleming18** [comment]
@schrodog I'm going to close this one as both @ardalis and I have had success after this changes mentioned in his comment. If you are still having trouble feel free to reply here or open another issue and we'd be happy to help out.
