### ISSUE TITLE
User interface leaves a lot to be desired

### ISSUE THREAD

**Issue by jeffhtu** [dotnet-architecture/eShopOnWeb#200]
I was excited to find this "reference" code, hoping to learn the proper coding techniques. Upon running the app, I have to say I'm somewhat disappointed the UI looks so...amateurish.  The header with stacked "My orders", "My account", "Log out", and the unusually tall footer with text that's not even centered.  I suppose the UI is not the focal point of this sample, but still...

Is there anything I can do to help? :-)

**Comment by ardalis** [comment]
Cleaning up the header UI has been on the backlog for a while (when logged in, it's way too tall). We would certainly welcome any PRs with UI improvements. Ideally keep them to one thing per PR so we can quickly review and implement them. Thanks!

**Comment by efleming18** [comment]
I've started to fix up the header and a few other styles as well.
https://github.com/dotnet-architecture/eShopOnWeb/pull/201
https://github.com/dotnet-architecture/eShopOnWeb/pull/202
Will continue making some improvements this week.

**Comment by efleming18** [comment]
- Added LibMan
- Added compilerconfig so now the sass files will compile down to css
https://github.com/dotnet-architecture/eShopOnWeb/pull/205

**Comment by efleming18** [comment]
Fixed the footer styling on the login page, checkout page, and any other page with less content on the screen in this PR.
https://github.com/dotnet-architecture/eShopOnWeb/pull/210

**Comment by efleming18** [comment]
Fixed the pager styles as well https://github.com/dotnet-architecture/eShopOnWeb/pull/215

**Comment by efleming18** [comment]
Updated the filter button styles https://github.com/dotnet-architecture/eShopOnWeb/pull/225

**Comment by efleming18** [comment]
I believe all of the above changes improved the UI to the point where any further updates should be new, separate issues.
