### ISSUE TITLE
why Cleaning up separate WebRazorPages proj

### ISSUE THREAD

**Issue by ghd258** [dotnet-architecture/eShopOnWeb#204]
why Cleaning up separate WebRazorPages proj

**Comment by ardalis** [comment]
Razor Pages is now covered in the single Web project, and is no longer new so the duplication isn’t valuable.

**Comment by ghd258** [comment]
Razor Pages is now covered in the single Web project  
 where adress？

**Comment by ardalis** [comment]
For example: https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Pages/Basket/Index.cshtml
