### ISSUE TITLE
Question: using separate DB context for Identity

### ISSUE THREAD

**Issue by JulidaRocks** [dotnet-architecture/eShopOnWeb#207]
An additional question:
Why do you use a separate Context for identity?
What are the advantages?
What would be the disadvantages of using on single context for everything?
Thanks a lot.

**Comment by efleming18** [comment]
Hey, @JulidaRocks , Separation of concerns is an advantage here. Keeping the identity, authentication, separate gives you the flexibility in the future to re-use it for another API, Web Project, etc. If you create a single DBContext, including identity, and you needed the same identity information in the future you would essentially be giving that application all of the business knowledge of the first application, which would be unnecessary and not true separation of concerns or single responsibility.

It can also help if you move to a microservices architecture like the [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) repository shows.

**Comment by JulidaRocks** [comment]
Thank you @efleming18
