### ISSUE TITLE
Create an Azure Build Pipeline for eShopOnWeb

### ISSUE THREAD

**Issue by ardalis** [dotnet-architecture/eShopOnWeb#209]
- Build everything
- Run all the tests
- Update a badge on README

**Comment by saschagottfried** [comment]
I recently finished learning path "[Build applications with Azure DevOps](https://docs.microsoft.com/en-us/learn/paths/build-applications-with-azure-devops/)" provided by Microsoft Learn. I would start to apply the first two modules to this project.

- Collaborate with others to build your applications using Azure Pipelines and GitHub
- Run automated tests in your pipeline to validate code quality

 Is this a viable approach that has support by project owners? Please indicate your support. Thanks.

**Comment by DavidJohnWilliams** [comment]
Hi, if you need help with creating the pipeline I would like to volunteer.

**Comment by efleming18** [comment]
@ardalis - Are you fine with me closing this issue as we are actually using GitHub Actions to run the build and all of the tests? It also updates the badge on the README.

![image](https://user-images.githubusercontent.com/1899987/80636889-27d9ca00-8a2c-11ea-96e1-43931783cce6.png)
