### ISSUE TITLE
Error when running docker-compose build

### ISSUE THREAD

**Issue by pada57** [dotnet-architecture/eShopOnWeb#211]
No error when building and running from VS2017 15.9.7
When running docker-compose build from directory where eShopOnWeb.sln is located

 ```
Restore completed in 71.47 ms for /app/src/ApplicationCore/ApplicationCore.csproj.
  Restore completed in 79.39 ms for /app/src/Infrastructure/Infrastructure.csproj.
  Restore completed in 11.86 ms for /app/src/Web/Web.csproj.

  Restore operation started...
  Restoring library jquery@3.3.1...
  Restoring library bootstrap@3.3.7...
  Restoring library jquery-validation-unobtrusive@3.2.10...
  Restoring library jquery-validate@1.17.0...
  Restoring library toastr.js@2.1.4...
  Restoring library @aspnet/signalr@1.0.3...

  6 libraries restored in 2.8 seconds

  ApplicationCore -> /app/src/ApplicationCore/bin/Release/netstandard2.0/ApplicationCore.dll
  Infrastructure -> /app/src/Infrastructure/bin/Release/netstandard2.0/Infrastructure.dll
 WebCompiler: Begin compiling compilerconfig.json
  WebCompiler installing updated versions of the compilers...
/root/.nuget/packages/buildwebcompiler/1.12.394/build/BuildWebCompiler.targets(12,9): error : No such file or directory [/app/src/Web/Web.csproj]
ERROR: Service 'eshopwebmvc' failed to build: The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
```

**Comment by asinelnikov** [comment]
Same error. VS2017 15.9.7. All NuGet packages updated to latest as of 21FEB2019.
Also tried different versions of BuildWebCompiler with no luck.

`PS E:\Projects\dotnet-architecture-monolith\src\Web> docker-compose build
Building eshopwebmvc
Step 1/11 : FROM microsoft/dotnet:2.2-sdk AS build
 ---> d5dbee97f68e
Step 2/11 : WORKDIR /app
 ---> Using cache
 ---> ed5281f973d4
Step 3/11 : COPY *.sln .
 ---> Using cache
 ---> c88d0bfc35f1
Step 4/11 : COPY . .
 ---> 92ee58c31a55
Step 5/11 : WORKDIR /app/src/Web
 ---> Running in cf86f3000e42
Removing intermediate container cf86f3000e42
 ---> b7a172833739
Step 6/11 : RUN dotnet restore
 ---> Running in d6af8d07a954
  Restoring packages for /app/src/ApplicationCore/ApplicationCore.csproj...
  Restoring packages for /app/src/Web/Web.csproj...
  Restoring packages for /app/src/Infrastructure/Infrastructure.csproj...
  Installing Ardalis.GuardClauses 1.2.8.
  Generating MSBuild file /app/src/ApplicationCore/obj/ApplicationCore.csproj.nuget.g.props.
  Generating MSBuild file /app/src/ApplicationCore/obj/ApplicationCore.csproj.nuget.g.targets.
  Restore completed in 2.26 sec for /app/src/ApplicationCore/ApplicationCore.csproj.
  Installing System.Security.Cryptography.Cng 4.4.0.
  Installing System.Memory 4.5.0.
  Installing Microsoft.EntityFrameworkCore.Analyzers 2.2.2.
  Installing Microsoft.EntityFrameworkCore.Abstractions 2.2.2.
  Installing System.Numerics.Vectors 4.4.0.
  Installing Microsoft.EntityFrameworkCore 2.2.2.
  Installing System.Buffers 4.4.0.
  Installing Microsoft.EntityFrameworkCore.Design 2.2.2.
  Installing Microsoft.EntityFrameworkCore.Relational 2.2.2.
  Installing Microsoft.EntityFrameworkCore.Tools 2.2.2.
  Installing Microsoft.EntityFrameworkCore.SqlServer 2.2.2.
  Generating MSBuild file /app/src/Infrastructure/obj/Infrastructure.csproj.nuget.g.props.
  Generating MSBuild file /app/src/Infrastructure/obj/Infrastructure.csproj.nuget.g.targets.
  Restore completed in 6.16 sec for /app/src/Infrastructure/Infrastructure.csproj.
  Installing System.Composition.Hosting 1.0.31.
  Installing System.Composition.Convention 1.0.31.
  Installing System.Composition.TypedParts 1.0.31.
  Installing System.Composition.Runtime 1.0.31.
  Installing System.Composition.AttributedModel 1.0.31.
  Installing System.Composition 1.0.31.
  Installing System.Linq.Parallel 4.3.0.
  Installing Microsoft.CodeAnalysis.Workspaces.Common 2.8.0.
  Installing Swashbuckle.AspNetCore 4.0.1.
  Installing Microsoft.Web.LibraryManager.Build 1.0.172.
  Installing Microsoft.CodeAnalysis.CSharp.Workspaces 2.8.0.
  Installing System.Runtime.Loader 4.3.0.
  Installing BuildWebCompiler 1.12.394.
  Installing NuGet.Frameworks 4.7.0.
  Installing Microsoft.VisualStudio.Web.CodeGeneration.Design 2.2.2.
  Installing Swashbuckle.AspNetCore.Swagger 4.0.1.
  Installing Swashbuckle.AspNetCore.SwaggerGen 4.0.1.
  Installing Microsoft.VisualStudio.Web.CodeGeneration.Contracts 2.2.2.
  Installing Microsoft.VisualStudio.Web.CodeGeneration.Utils 2.2.2.
  Installing Microsoft.VisualStudio.Web.CodeGeneration.Templating 2.2.2.
  Installing Microsoft.AspNetCore.Http.Features 2.0.0.
  Installing System.Runtime.CompilerServices.Unsafe 4.4.0.
  Installing Microsoft.VisualStudio.Web.CodeGeneration.Core 2.2.2.
  Installing Swashbuckle.AspNetCore.SwaggerUI 4.0.1.
  Installing System.Text.Encodings.Web 4.4.0.
  Installing Microsoft.VisualStudio.Web.CodeGenerators.Mvc 2.2.2.
  Installing Microsoft.AspNetCore.Mvc.Formatters.Json 2.0.0.
  Installing Microsoft.Extensions.Localization.Abstractions 2.0.0.
  Installing Microsoft.AspNetCore.Mvc.Core 2.0.0.
  Installing Microsoft.AspNetCore.Authentication.Abstractions 2.0.0.
  Installing Microsoft.AspNetCore.Authorization 2.0.0.
  Installing Microsoft.AspNetCore.Mvc.ApiExplorer 2.0.0.
  Installing Microsoft.AspNetCore.Mvc.DataAnnotations 2.0.0.
  Installing Microsoft.AspNetCore.Routing 2.0.0.
  Installing Microsoft.Extensions.FileProviders.Embedded 2.0.0.
  Installing Microsoft.AspNetCore.StaticFiles 2.0.0.
  Installing Microsoft.VisualStudio.Web.CodeGeneration 2.2.2.
  Installing Microsoft.AspNetCore.JsonPatch 2.0.0.
  Installing Microsoft.AspNetCore.WebUtilities 2.0.0.
  Installing Microsoft.Extensions.Logging.Abstractions 2.0.0.
  Installing Microsoft.Net.Http.Headers 2.0.0.
  Installing Microsoft.Extensions.DependencyModel 2.0.0.
  Installing Microsoft.AspNetCore.Http.Abstractions 2.0.0.
  Installing System.Diagnostics.DiagnosticSource 4.4.1.
  Installing Microsoft.AspNetCore.ResponseCaching.Abstractions 2.0.0.
  Installing Microsoft.Extensions.FileProviders.Abstractions 2.0.0.
  Installing Microsoft.AspNetCore.Hosting.Abstractions 2.0.0.
  Installing Microsoft.Extensions.Configuration.Abstractions 2.0.0.
  Installing Microsoft.AspNetCore.Mvc.Abstractions 2.0.0.
  Installing Microsoft.AspNetCore.Http.Extensions 2.0.0.
  Installing Microsoft.AspNetCore.Authorization.Policy 2.0.0.
  Installing Microsoft.AspNetCore.Authentication.Core 2.0.0.
  Installing Microsoft.AspNetCore.Hosting.Server.Abstractions 2.0.0.
  Installing Microsoft.AspNetCore.Http 2.0.0.
  Installing Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0.
  Installing System.ComponentModel.Annotations 4.4.0.
  Installing Microsoft.Extensions.Localization 2.0.0.
  Installing Microsoft.Extensions.ObjectPool 2.0.0.
  Installing Microsoft.Extensions.Options 2.0.0.
  Installing Microsoft.AspNetCore.Routing.Abstractions 2.0.0.
  Installing Microsoft.Extensions.WebEncoders 2.0.0.
  Installing Microsoft.Extensions.Hosting.Abstractions 2.0.0.
  Installing Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 2.2.2.
  Installing Microsoft.CSharp 4.4.0.
  Installing Microsoft.DotNet.PlatformAbstractions 2.0.0.
  Installing Microsoft.Extensions.Primitives 2.0.0.
  Generating MSBuild file /app/src/Web/obj/Web.csproj.nuget.g.props.
  Generating MSBuild file /app/src/Web/obj/Web.csproj.nuget.g.targets.
  Restore completed in 13.28 sec for /app/src/Web/Web.csproj.
Removing intermediate container d6af8d07a954
 ---> 6a7fb06b1b4f
Step 7/11 : RUN dotnet publish -c Release -o out
 ---> Running in cc844b05fd09
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 66.32 ms for /app/src/ApplicationCore/ApplicationCore.csproj.
  Restore completed in 68.79 ms for /app/src/Infrastructure/Infrastructure.csproj.
  Restore completed in 89.61 ms for /app/src/Web/Web.csproj.

  Restore operation started...
  Restoring library jquery@3.3.1...
  Restoring library bootstrap@3.3.7...
  Restoring library jquery-validation-unobtrusive@3.2.10...
  Restoring library jquery-validate@1.17.0...
  Restoring library toastr.js@2.1.4...
  Restoring library @aspnet/signalr@1.0.3...

  6 libraries restored in 3.09 seconds

  ApplicationCore -> /app/src/ApplicationCore/bin/Release/netstandard2.0/ApplicationCore.dll
  Infrastructure -> /app/src/Infrastructure/bin/Release/netstandard2.0/Infrastructure.dll

  WebCompiler: Begin compiling compilerconfig.json
  WebCompiler installing updated versions of the compilers...
/root/.nuget/packages/buildwebcompiler/1.12.394/build/BuildWebCompiler.targets(12,9): error : No such file or directory [/app/src/Web/Web.csproj]
ERROR: Service 'eshopwebmvc' failed to build: The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
PS E:\Projects\dotnet-architecture-monolith\src\Web>`

**Comment by efleming18** [comment]
@pada57 @asinelnikov I have a fix out for this now. The fix is actually very simple. Like you called out, @asinelnikov the issue is in the `BuildWebCompiler` package. There are some Windows-specific commands in it so on Linux containers, it would work. I switched to Windows containers locally and tried it out and sure enough everything worked fine. This is obviously not ideal though. For now, I'm removing the NuGet package that would enable the `WebCompiler` tasks to run on build.

The WebCompiler relates to the `compilerconfig.json` and enables us to make changes to the sass `(.scss)` files and will automatically compile those files down to the necessary `css` files. I'll be using a different method to accomplish that, but for now the Docker support is more important. If we have to make any css changes before I get a fix in, we'll need to compile the scss manually. I'll hopefully have a fix for that this week though.

Give it a try now and make sure it's working again for you. If not, please let me know.

**Comment by pada57** [comment]
Thanks @efleming18  it works fine with current fix
Could you use WebCompiler only for dev in visual studio and run sass cli command when building docker image ?
