### ISSUE TITLE
Filter and paging are not compatible

### ISSUE THREAD

**Issue by tranvannhatdev** [dotnet-architecture/eShopOnWeb#212]
Hi,

I have review this project and this is great. But i have a issue for you.
In the Catalog index page cannot filter than paging
Example:
I filter with .net type result 10 and next page to result 0 or cannot next page.
But in the current that result 2 record because:
when you click next page, filter model is null.
This is project issue or .Net core issue?

I think we request with model, This page model does not reset to null value.
Please let me know if you have concern.

**Comment by ardalis** [comment]
@efleming18 can you repro and fix next chance you get?

**Comment by efleming18** [comment]
I will take a look @ardalis @tranvannhatdev !
