### ISSUE TITLE
Order does not have a Foreign Key to BuyerId

### ISSUE THREAD

**Issue by vertonghenb** [dotnet-architecture/eShopOnWeb#214]
Currently there is no FK relationship between an `Order` and a `Buyer`. The code however makes sure this never occurs, but in the database, it's not guaranteed.

https://github.com/dotnet-architecture/eShopOnWeb/blob/be54fd48bb36df8bc0be62400c85e746f98903d4/src/ApplicationCore/Entities/OrderAggregate/Order.cs#L17

**Comment by efleming18** [comment]
Hey @vertonghenb - That should be ok to enforce it in code. BuyerId here is not actually a GUID, but rather an email address. We generate a random GUID for a BuyerId, but once the user creates an account it becomes their Email address. 

We also want to keep this out in case we ever wanted to move to microservices, decoupling Orders and Baskets, etc; which would also decouple the entities around in the database. I believe [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) may take a look at this.
