### ISSUE TITLE
Question: What seperate concerns do IRepository and IAsyncRepository serve?

### ISSUE THREAD

**Issue by devingoble** [dotnet-architecture/eShopOnWeb#216]
Besides the obvious of async, what is the intended use for these two interfaces? They don't overlap functionality completely, and they're used in different places. What's the logic for how and when either of these are intended to be used?

**Comment by efleming18** [comment]
Hey @devingoble - I believe the `IRepository` is just a little dated and hasn't been removed yet. In my opinion we should get rid of the `IRepository` and switch to only the `IAsyncRepository`, moving over any missing functionality. I can work on cleaning this up. Thank you for calling it out!
