### ISSUE TITLE
Unit tests do not compile

### ISSUE THREAD

**Issue by opty-net** [dotnet-architecture/eShopOnWeb#22]
Missing `GetImage()` action from `CatalogController`.

**Comment by ardalis** [comment]
Weird. Last PR should have fixed that. I will check it out tonight but those tests are to be removed as that method is not needed.

**Comment by isabasan** [comment]
It's really bad to see some compilation errors in a guideline project :(

**Comment by ardalis** [comment]
Fixed by #23
