### ISSUE TITLE
Use ThenInclude in SpecificationEvaluator class 

### ISSUE THREAD

**Issue by andresroingsis** [dotnet-architecture/eShopOnWeb#222]
How to use ThenInclude in SpecificationEvaluator class  ?

![image](https://user-images.githubusercontent.com/46057124/53969470-dacbc380-40c6-11e9-99cd-e2c721191b24.png)

**Comment by ardalis** [comment]
You can't, but you can use "Foo.Bar" notation to include sub-properties. See for instance:
https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Specifications/CustomerOrdersWithItemsSpecification.cs#L11

This is why the string-based includes are supported by the specification.

**Comment by andresroingsis** [comment]
Great!.. thanks

**Comment by mrukas** [comment]
In case someone still wants to have this feature. I added a pull request that adds the possibility to chain includes with .Include() and .ThenInclude().
[https://github.com/dotnet-architecture/eShopOnWeb/pull/331/commits/c3193b10cdff0bf5b1c41ac4a14e75b6ee1fb786](https://github.com/dotnet-architecture/eShopOnWeb/pull/331/commits/c3193b10cdff0bf5b1c41ac4a14e75b6ee1fb786)
