### ISSUE TITLE
How to avoid referencing the Infrastructure project in the UI

### ISSUE THREAD

**Issue by zHaytam** [dotnet-architecture/eShopOnWeb#228]
I'm wondering how would someone go about avoiding to reference the Infrastructure project from the UI (since it's considered better, no?).

Quoting the note from https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/common-web-application-architectures#ui-layer-types:

> In order to wire up dependency injection in ConfigureServices in the Startup.cs file of the UI project, the project may need to reference the Infrastructure project. This dependency can be eliminated, most easily by using a custom DI container. For the purposes of this sample, the simplest approach is to allow the UI project to reference the Infrastructure project.

**Comment by efleming18** [comment]
Hey @zHaytam - Great question. I'll leave this one for @ardalis to give more insight to. He wrote a blog post a few years ago on this subject if you'd like to look at it and ask any further questions here. https://ardalis.com/avoid-referencing-infrastructure-in-visual-studio-solutions

**Comment by efleming18** [comment]
I'm going to close this @zHaytam - if you have more questions though, let us know.

**Comment by oyhan** [comment]
Hi.Excuse me but its funny that no body on net nor none of Clean Architecture samples implemented this concept. All samples just expressed that you must avoid the reference to Infrastructure layer and the whole did the opposite .

**Comment by ardalis** [comment]
It’s certainly not that you must not, but you shouldn’t outside of Startup (or wherever you wore up the application’s services). Using project references is just the de facto standard so we keep it mainly for that reason.
