### ISSUE TITLE
Where to put Razor Email Templates?

### ISSUE THREAD

**Issue by zHaytam** [dotnet-architecture/eShopOnWeb#231]
Hello,

For now, I've been using Razor Email templates with FluentEmail and I used to put it on the same project, but since I switched to this clean architecture I want to know where to best put them?

Should they be in the Infrastructure alongside the implementation of the `EmailSender`?
The templates are embedded resources so I would need to access the assembly that has them.

Thank you!

**Comment by netferret** [comment]
Hi,

The first question I would ask is how often would this email change?, if the answer is often then might want to put this in something that can be changed quickly without a redeployment of the whole solution, another separated service or database(depends on the scale etc).  

If its not going to change often then storing in a resource shouldn't cause any problems in my opinion and seems to make sense.

To answer your question, I would say it would sit in infrastructure in my opinion.

**Comment by efleming18** [comment]
Hi @zHaytam - reading over this now. I'm not very familair with FluentEmail, I'm assuming it's [this](https://github.com/lukencode/FluentEmail)? Quickly looking through it, it seems similar to something like [SendGrid](https://sendgrid.com/), which is actually what I was going to use to implement in the repo as an example. Looking even more closely, it looks like FluentEmail has a SendGrid integration that you can use.

With using SendGrid my plan was to keep everything email related in the same place. With the `EmailSender` being in the Infrastructure project, if it would require a template I would want to keep it in the Infrastructure project as well. Although, looking at this again, I need to think about whether or not the `EmailSender` class/functionality belongs in Infrastructure or not, and rather should be in `ApplicationCore`, but that's outside of the scope of this question.

As @netferret pointed out, if templates are constantly changing and you need to be able to move quickly with them, then creating a new microservice to handle it would likely be something you'd need to consider although spinning your own would likely turn in quite a bit of work. Something like SendGrid allows you to store specific templates in your account, and then you can specify which one is used when invoking the SendGrid API.

Does that help? What other questions might you have?

**Comment by zHaytam** [comment]
Yes, it helps, thank you both!
