### ISSUE TITLE
Question: How to access a repository from a specification?

### ISSUE THREAD

**Issue by eb-clickfusion** [dotnet-architecture/eShopOnWeb#232]
If I wanted to access a repository (or a db context) from within a specification class, how would I achieve this? For example, if I wanted to build a complex `Criteria` which required a trip to the database before a separate query was run.

**Comment by efleming18** [comment]
Hi @eb-clickfusion - I think I would recommend against doing something like that. A specification is something that you should only pass in a result set from a DB query to. Everything the specification needs should be passed in to it.

Do you have maybe a more concrete example for me to consider?

**Comment by eb-clickfusion** [comment]
Hi @efleming18, thanks for the response. I need to filter records in a table based on user access. My table has a `RoleId` field so I can pass this through to the specification and do `x => x.RoleId == roleId` but it needs to be more complex than that. Roles are hierarchical so I really need to find out which roles the user has access to first (via the db), then include that in my specification. For example `x => new [] { 1, 2, 3 }.Contains(x.RoleId)`

**Comment by ardalis** [comment]
Then get the array of role IDs first, and pass *that* into the specification constructor.

**Comment by eb-clickfusion** [comment]
Thanks @ardalis. 

If I need to pass the array of role IDs in to a number of different specification constructors, I guess I can create a `GetRolesForUser()` method on a UserRepository (or UserRoleRepository) and call that before running the specification constructor?

**Comment by ardalis** [comment]
Sure, and that's also probably a very cacheable call. Caching it may make up for the fact that otherwise it could be more expensive since it'll be two calls instead of a single (complex) JOIN query that you might otherwise have been able to run.

**Comment by eb-clickfusion** [comment]
Great, thanks. I'll take a look at your CachedRepository blog post.

One final question - where would be best to call the `GetRolesForUser()` method from? I would need to have access to the current user identity and the db context. Perhaps `EfRepository` if I inject the identity?

**Comment by ardalis** [comment]
You shouldn't need to inject "the identity" but rather just pass that method the userId (probably a GUID).

You could call it from wherever you were going to call the method with your complex criteria. If that was from, say, a controller action, then I would probably recommend wrapping that up into a service if only to keep your controller smaller and your code more testable and potentially reusable.
