### ISSUE TITLE
Make example cross-platform

### ISSUE THREAD

**Issue by tidyui** [dotnet-architecture/eShopOnWeb#234]
The example uses `LocalDb` as development which is only a valid option on Windows. Using `SQLite` as development database will work on all platforms.

**Comment by dhulwells** [comment]
Can I take this one?

**Comment by efleming18** [comment]
@dhulwells Sure! Feel free. If you do end up working on it and get a PR out there, link it to this issue and/or tag me so I can take a look.

**Comment by tidyui** [comment]
I was thinking about doing it myself, but as it requires throwing away and recreating the migrations I wasn't sure how you wanted to handle it.

**Comment by newtonsheikh** [comment]
even better may be a mongoDB or CosmosDB one.

**Comment by efleming18** [comment]
@dhulwells Any update/progress here? If not, I'm happy to take a crack at it too.

**Comment by jahbenjah** [comment]
I'm working on this issue but have problems on how to manage  `.ForSqlServerUseSequenceHiLo("")` in SQLite . Using this SQL Server's specific stuff violates the [Persistence ignorance](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles#persistence-ignorance) principal.

**Comment by RaulButuc** [comment]
Any progress on this? Are we planning on using K8s deployments here?

**Comment by tidyui** [comment]
@jahbenjah As of EF Core 3.0 all migrations are completely dependent on the database they were built for which you probably know. As I manage @piranhacms we have solved this by having the DbContext and data repositories in one project and then have separate projects for the migrations for each database. This way you keep the logic in one place but let’s the user decide which migration package should be used:

https://github.com/PiranhaCMS/piranha.core/tree/master/data

Regards

**Comment by efleming18** [comment]
I've been giving this one some thought. Instead of updating the base of the application to use SQLite, would it be fair to have folks on other platforms use the provided docker configurations?

**Comment by efleming18** [comment]
I'm going to close this one but if there is further discussion needed, we can re-open and have those discussions.
