### ISSUE TITLE
Show Mediatr Use with Controllers or Pages

### ISSUE THREAD

**Issue by ardalis** [dotnet-architecture/eShopOnWeb#239]
Demonstrate how to use the Mediatr package/pattern to simplify logic in Controllers/Pages.

**Comment by efleming18** [comment]
This is finished in [this branch](https://github.com/dotnet-architecture/eShopOnWeb/tree/mediatr-example)

**Comment by ofrades** [comment]
Where is Mediatr implementation explained?
