### ISSUE TITLE
Services in ApplicationCore that need almost the same fields as a long ViewModel

### ISSUE THREAD

**Issue by zHaytam** [dotnet-architecture/eShopOnWeb#245]
Hello,

I have a pretty full ViewModel consisting of fields that users needs to input(7 or 8) and I wanted to create a service that handles this.

Is it okay to have a method in my service that expects 7-8 arguments or is it too long?
Should I create a struct between the controller (viewmodel) and the service?

Thank you!

**Comment by ardalis** [comment]
More than 2-3 parameters/arguments is where I start to consider refactoring. More than 7 or so and it's pretty definite. It's even a default rule for NDepend at that point: https://www.ndepend.com/default-rules/NDepend-Rules-Explorer.html?ruleid=ND1004#!

How to refactor would depend on where the service lives. If it lives in the web project, then you could just have it work directly with the ViewModel/APIModel type that is coming in via model binding. If the service lives in your Core project, though, then it should only work with domain types, ideally. Sometimes it makes sense to define some DTOs in the Core project to facilitate these services, but I try to avoid that unless I don't have a better solution.

Hope that helps. There's no one "right" answer - it's a matter of what you find works well for you and your team.

**Comment by zHaytam** [comment]
If I may (and this is I think a seperate question):
We know that the ViewModel has validation attributes, but if I pass the ViewModel's properties to a Service, do I need to re-validate them or just trust it?

**Comment by efleming18** [comment]
In my opinion, most of the time I would trust it. If you don't, then you start having to maintain your own validation on top of what is already provided for you in the validation attributes. It forces you to maintain two sets of validation, which could actually cause problems/bugs if you change it in one place and not the other.
