### ISSUE TITLE
Wiki image wrong on Troubleshooting at 05 (Wiki)

### ISSUE THREAD

**Issue by doggy8088** [dotnet-architecture/eShopOnWeb#250]
Here at [Troubleshooting](https://github.com/dotnet-architecture/eShopOnWeb/wiki/05.-Running-locally-on-a-Windows-Container-from-VS-2017#troubleshooting)'s screenshot is wrong.  The screenshot should shows `Switch to Windows containers`.

![image](https://user-images.githubusercontent.com/88981/58027017-4eb82c80-7b4a-11e9-84e8-0a57ae280815.png)

**Comment by efleming18** [comment]
Thanks @doggy8088 - I've created a new image and will update the Wiki doc. 
![image](https://user-images.githubusercontent.com/1899987/58523377-3b344380-8192-11e9-822e-550a23a4b6d5.png)
