### ISSUE TITLE
When published not all CSS are included

### ISSUE THREAD

**Issue by jvilimek** [dotnet-architecture/eShopOnWeb#254]
After I publish the site to my own app service (web project), there are missing CSS files included in the shared layout view = the site is missing images, feels ugly etc.

* download the sources, build&run locally, setup DB etc. It's working fine.
* but once I **publish** the **Web** project (from within Visual Studio -> Publish) the layout of the site is broken

I have find out in \src\Web\Views\Shared\_Layout.cshtml there are lots of CSS missing in head under "<environment names="Staging,Production">" tag.

**Comment by jvilimek** [comment]
I have already created a fix for this, see https://github.com/dotnet-architecture/eShopOnWeb/pull/255
(not sure, how to associate it)

**Comment by efleming18** [comment]
Resolved with the merged PR above. Thanks @jvilimek
