### ISSUE TITLE
BasketItem is not an aggregate, so it should not have a repository

### ISSUE THREAD

**Issue by storms-lab** [dotnet-architecture/eShopOnWeb#260]
BasketItem is not an aggregate, so it should not have a repository. The need for the BasketItem repository could be removed by changing the implementation of DeleteBasketAsync.

![image](https://user-images.githubusercontent.com/51679664/59224505-8ee45b00-8b9c-11e9-80c5-fd4310458db1.png)

**Comment by CESARDELATORRE** [comment]
I agree on that. Only Aggregate-Root should have related repository classes.

**Comment by ardalis** [comment]
Yeah, we were looking at it together in my workshop today :). We'll get it updated.
