### ISSUE TITLE
IAsyncRepository does not enforce <T> being an IAggregateRoot

### ISSUE THREAD

**Issue by storms-lab** [dotnet-architecture/eShopOnWeb#261]
`where T : BaseEntity` should become `where T : BaseEntity, IAggregateRoot` ?

![image](https://user-images.githubusercontent.com/51679664/59224827-4bd6b780-8b9d-11e9-9c39-e0d809f62415.png)

**Comment by efleming18** [comment]
@storms-lab Totally agree here. I've [started to address it](https://github.com/dotnet-architecture/eShopOnWeb/pull/264) by first removing the BasketItems repository as you pointed out in https://github.com/dotnet-architecture/eShopOnWeb/issues/260.

Enforcing this exposes a few more (CatalogType, CatalogBrand, CatalogItems) that need to be addressed as well. I would like to take an iterative approach to fixing them one at a time to avoid a massive PR so I will enforce it as you suggest here once I have those fixed up. Thanks for calling this out.

**Comment by efleming18** [comment]
This PR closes this issue: https://github.com/dotnet-architecture/eShopOnWeb/pull/273
