### ISSUE TITLE
Capitalize ISpecification<T>'s isPagingEnabled Property

### ISSUE THREAD

**Issue by JohnCOsborne** [dotnet-architecture/eShopOnWeb#277]
A very minor detail but it caught my eye. I'm assuming you want it to be capitalized.

**Comment by ardalis** [comment]
Agreed. Want to do a quick PR?

**Comment by JohnCOsborne** [comment]
Sure thing.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by efleming18** [comment]
Closed by: https://github.com/dotnet-architecture/eShopOnWeb/pull/280
