### ISSUE TITLE
Unneeded dependency to Microsoft.AspNetCore.Mvc on the UnitTests project.

### ISSUE THREAD

**Issue by lesair** [dotnet-architecture/eShopOnWeb#279]
The UnitTests project has an unused dependency on Microsoft.AspNetCore.Mvc.

This project should not have ASP.NET framework dependencies since unit tests are not concerned with testing logic that depends on frameworks.

**Comment by escalonn** [comment]
Maybe related to [this not-documented-everywhere-it-should-be item](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#test-app-prerequisites), but still not doing it quite right.

**Comment by lesair** [comment]
@escalonn, the reference you sent is for integration tests, but this issue is about unit tests.

**Comment by escalonn** [comment]
It does concern unit tests also - that's what I mean about not documented everywhere it should: dotnet/docs#13455

**Comment by lesair** [comment]
@escalonn, thank you for the clarification.
