### ISSUE TITLE
IAppLogger seems redundant

### ISSUE THREAD

**Issue by jbrinkman** [dotnet-architecture/eShopOnWeb#283]
The current implementation of IAppLogger seems unnecessary unless the sole purpose is to limit the logging API. ILogger is already part of the basic stack and fully abstracts any specific providers. My specific providers (Serilog in my case) are configured in the web tier during startup and after that I can just use ILogger everywhere else (including in my tests) using DI.

Is there some benefit to IAppLogger that I am overlooking?

**Comment by fiseni** [comment]
In case you use only .net core web projects, then yes it's redundant, and most of the providers can be added on the fly. But, what if on same base code you use winform/wpf ui project targeting .net framework?

I guess here it is added just as an example construct, what u might do if u need it (not that it's really necessary in this case).

**Comment by jbrinkman** [comment]
Fair enough. Is that worth adding some code comments? I always worry when viewing sample apps that the underlying reasons for a particular implementation detail are unknown which leads to cargo culting.

**Comment by fiseni** [comment]
Honestly, I'm not even sure if that's the real reason, it was just my assumption. The project maintainers might clarify the real intentions. I personally always use adapters for logging (microsoft, log4net) and DI (microsoft, autofac, ninject). But thats based on my use cases. Usually I work on several UI projects on top of same code base, so it's totally worth it.

**Comment by ardalis** [comment]
This blog post sums up the value in having your own interface that you own for logging:
https://ardalis.com/testing-logging-in-aspnet-core

**Comment by efleming18** [comment]
Any other questions or concerns on this one @jbrinkman ?

**Comment by jbrinkman** [comment]
Thanks for the post @ardalis . I am very much against cargo cult programming and like to know why I am implementing something rather than just assuming the feature is the right one in every situation.

**Comment by ardalis** [comment]
Sure thing. If it weren't for the fact that logging in ASP.NET Core is heavy on extension methods, making it difficult to mock, it wouldn't have caused enough pain to have been worth the adapter, IMO. But when actually trying to do it, it was way easier with an interface you yourself own.
