### ISSUE TITLE
Specification not returning results

### ISSUE THREAD

**Issue by Edgias** [dotnet-architecture/eShopOnWeb#287]
I am developing a project using this architecture as an example. I have encountered an issue where my specification is not returning data. I have an entity LeadSource which has two properties Name and Description. I created a LeadFilterSpecification where a search string may be supplied. In the event that its null or empty I want to return data based on the pagination parameters supplied.

`public class LeadSourceFilterSpecification : BaseSpecification<LeadSource>
    {
        public LeadSourceFilterSpecification(int skip, int take, string searchString)
            :base(ls => (!string.IsNullOrEmpty(searchString) || ls.Name.ToUpper().Contains(searchString)))
        {
            ApplyOrderBy(ls => ls.Name);
            ApplyPaging(skip, take);
        }
    }`

I am debugging the application in VS 2019: skip is 0, take 10, and searchString is null. There are two records currently in the db but the app is not returning any records. I expect all the records to be returned since searchString is null.

What am I doing wrong?

**Comment by gabor-rajczi** [comment]
Hello!

Try invert the condition on searchString.
`ls => (string.IsNullOrEmpty(searchString) || ls.Name.ToUpper().Contains(searchString))`
Because You want all entity when the searchString is null or empty.

**Comment by efleming18** [comment]
Thanks for the quick reply on this @gabor-rajczi ! 

@Edgias Let us know if that does the trick for you!

**Comment by Edgias** [comment]
It worked. Thanks @gabor-rajczi. I was following the CatalogFilterSpecification though its an int. [https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Specifications/CatalogFilterSpecification.cs](url). I thought it will work the same.

**Comment by efleming18** [comment]
Great to hear @Edgias! 
Thanks again, @gabor-rajczi!
