### ISSUE TITLE
Business logic

### ISSUE THREAD

**Issue by expressiveco** [dotnet-architecture/eShopOnWeb#303]
Would not it be better to handle following as business logic in a single method of a domain model; in a service or a separate domain model class?
Because users of those services might be confused which methods to use and in which order they should call.
https://github.com/dotnet-architecture/eShopOnWeb/blob/99c416142fcdf130842d8b24a50943765ad7fd8b/src/Web/Pages/Basket/Checkout.cshtml.cs#L43-L54

**Comment by efleming18** [comment]
Any further questions here before I close this @expressiveco?

**Comment by bilisimofis** [comment]
no thank you

**Comment by expressiveco** [comment]
thank you
