### ISSUE TITLE
IIdentityParser implementation?

### ISSUE THREAD

**Issue by dylinmaust** [dotnet-architecture/eShopOnWeb#304]
It seems that this interface is missing an implementation. Is that intentional?

**Comment by efleming18** [comment]
Hey @dylinmaust  - good call out! It does not appear that has been used in some time so I went ahead and cleaned it up.

**Comment by dylinmaust** [comment]
Thanks @efleming18 - In that case, I think the ApplicationCore nuget dependency on System.Security.Claims could be removed as well.
