### ISSUE TITLE
Ajax Exception handling.

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#306]
Hello Team,

Thanks for this wonderful project. I have a question regarding Exception handling. #299 explains exception handling. But what about AJAX scenarios? Let's say I make a ajax request to perform a operation. and the domain entity throws an error. How will this be handled and notified to the user? Please assist

Thanks,
Abdul

**Comment by efleming18** [comment]
Hey @fingers10 - thanks for the question! Are you talking about something like an invalid input to a text box and how that is returned to the user?

For example, someone trying to log in to the site and not entering an email or a password before clicking "Login"? In this scenario, we would return errors to them on the frontend like so: 
![image](https://user-images.githubusercontent.com/1899987/65561059-1a48e880-df0f-11e9-8336-1788ec94e2e3.png)

This type of validation can be done using [model validation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.0) and you can see this in the code [here](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Areas/Identity/Pages/Account/Login.cshtml.cs#L40).

Does this help to answer your question?

**Comment by fingers10** [comment]
@efleming18 These are all input validations which we can achieve through annotations. What about exceptions? If we are making an normal form post and some exception happens, the below code with catch that in production and will display error page.

```c#
if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseShowAllServicesMiddleware();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
```

But what about AJAX post? Instead of making an form post, I'm making an AJAX post and same exception happens. Now how to display "Internal Server Error" message to user?

**Comment by efleming18** [comment]
In the example [I mention creating in the next few days](https://github.com/dotnet-architecture/eShopOnWeb/issues/308), this should be covered as well.

**Comment by efleming18** [comment]
Hey @fingers10 sorry for the delay! Please take a look at this PR I have out there: https://github.com/dotnet-architecture/eShopOnWeb/pull/312

I tried to explain what I was doing and why in each commit, to show a progression of how I got to where it ended up. If you have any further questions though, let's open up another issue to discuss? I recommend a new issue as I think the other issues are all interconnected and centralizing to one issue will help us keep things straight!
