### ISSUE TITLE
Admin Page Sample to add Items, brands, etc.

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#307]
Hello Team,

Can you please add a admin page sample to add items, brands, etc? Because these mostly involves CRUD and I want to learn how to do CRUD in DDD approach.

Thanks,
Abdul

**Comment by efleming18** [comment]
Hey @fingers10 - this would be an interesting addition!

@ardalis - what are your thoughts on this to be added to the sample?

**Comment by ardalis** [comment]
I think it would be a great addition.

**Comment by fingers10** [comment]
That sounds great. Any plans on this?

**Comment by efleming18** [comment]
@fingers10 We'll likely be working on the upgrade to .NET Core 3.0 starting very soon, so I'd imagine we'll wait and add this functionality right after so we don't conflict in the middle of the upgrade. I'll be sure to keep you in the loop on progress!

**Comment by fingers10** [comment]
@efleming18 please can you also add a AJAX example of doing CRUD with this Admin Page Sample?

**Comment by efleming18** [comment]
Hey @fingers10 - I'm not sure if adding that example would be in scope for this project.

As for the original request I added the ability to modify a few existing properties on a catalog item to demonstrate some admin capabilities here: https://github.com/dotnet-architecture/eShopOnWeb/pull/324
