### ISSUE TITLE
Notifications sample

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#308]
Hello Team,

Please can you add some example to show notifications? In current project, lets say an order is placed. How to notify end user? In Ajax scenarios, a toast like approach? Like how gmail toast like notification at bottom right when an email is sent..

Thanks,
Abdul

**Comment by efleming18** [comment]
Hey @fingers10 - I could see something like sending a confirmation email that the order has been received being in scope for the project over a toast notification. I had stubbed out sending an account activation confirmation email via SendGrid and SMTP in the past, but it was only a branch. We could potentially revisit that.

@ardalis thoughts? In scope for this sample?

**Comment by fingers10** [comment]
@efleming18 Thanks for the quick response. Notifying User via email is fine. How to notify via UI without page redirect. Lets forget the order example and imagine we are in a AJAX based page. All operations are ajax based.

I'm doing a Ajax post to the server and everything goes well. Now email will be triggered from server and how the end user will be notified in screen? 

Or this would be a perfect example - Let's say we have a items grid in UI and we are adding a new item to the database we need to make sure that item doesn't already exists in database if exists we need to show item already exists message to user via notification and if the item is new then it needs to be saved to database and item added successfully message needs to be show to user or even some failure happens Internal Server Error should be notified to the user. All these should happen via AJAX. 

Any helps on this would be much appreciated.

Thanks,
Abdul

**Comment by fingers10** [comment]
@efleming18 Or even you can consider these scenarios. In a Ajax call user does a post and after processing business rules, the server notifies the user with a yes or no choice. Based on the yes or no action from the user the server needs to proceed accordingly. 

Thanks,
Abdul

**Comment by efleming18** [comment]
Hey @fingers10 - I see what you're asking now. Let me work on an example in a separate branch for you in the next couple days? I think the addition you recommended here https://github.com/dotnet-architecture/eShopOnWeb/issues/307 will actually provide some insight in to many of the questions you are asking. The full implementation of that is probably a few weeks out as we're going to try and get to the .NET Core 3.0 upgrade here soon. But, let me try and throw together a quick example in the next few days for to get us by in the meantime. How does that sound?

You won't want to return something like an "Internal Server Error" back to the user. You would want to handle that before returning it to the user. The same goes for returning just a "yes or no" answer to the user as well after running through the business logic. There are ways to do this.

I will come up with an example for you soon and report back here.

**Comment by fingers10** [comment]
@efleming18 Thanks for the support and I'm excited and curious to see the changes along with .NET Core 3.0 update.

**Comment by efleming18** [comment]
Hey @fingers10 sorry for the delay! Please take a look at this PR I have out there: https://github.com/dotnet-architecture/eShopOnWeb/pull/312

I tried to explain what I was doing and why in each commit, to show a progression of how I got to where it ended up. If you have any further questions though, let's open up another issue to discuss? I recommend a new issue as I think the other issues are all interconnected and centralizing to one issue will help us keep things straight!
