### ISSUE TITLE
Where to add Business rules/Validations

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#309]
Hello Team,

The current project sample doesn't have any examples showing how to add business rules/validations and notify user. Please can you assist on where these needs to be added in DDD approach?

Thanks,
Abdul

**Comment by efleming18** [comment]
Hey @fingers10 - with how small this project is, it is a little difficult to fit many examples of business rules/validations in to it. I think you could consider something like the [OrderService](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Services/OrderService.cs) and the [BasketService ](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Services/BasketService.cs) as business rules. This is abstracting something "the business" has deemed as the functionality they want. In DDD you'd want to abstract all the functionality out from the Web layer and in to the ApplicationCore.

For example, updating the number of items in basket, removing items, or even deleting the basket altogether once you've checked out can be handled in the service that lives in ApplicationCore. 

Validation on the other hand can be done on the models, like I talk about [here](https://github.com/dotnet-architecture/eShopOnWeb/issues/306#issuecomment-534807489).

I'm trying to think of a place where we could add a more straightforward example of a typical business rule. We may be able to demonstrate it through doing something like you mentioned in https://github.com/dotnet-architecture/eShopOnWeb/issues/307 or https://github.com/dotnet-architecture/eShopOnWeb/issues/308.

Has this helped? What other questions might you have?

**Comment by fingers10** [comment]
@efleming18 Again thanks for your time and response.

For example for some reason after doing some business check the user is not allowed to place an order under specific scenarios and when he places an order how to display the message that the "user cannot place a order"? At least some thing like before placing an order, we can do some check like _orderService.CanPlaceOrder() ? and if this is true user can place order and if fails then corresponding message needs to be displayed to the user.

I think all my questions are interconnected. Probably Admin Page Sample #307 should address all these. Or whatever I'm asking is only possible with SPA like Blazor and not in a normal web app?

Thanks,
Abdul

**Comment by efleming18** [comment]
Hey @fingers10 sorry for the delay! Please take a look at this PR I have out there: https://github.com/dotnet-architecture/eShopOnWeb/pull/312

I tried to explain what I was doing and why in each commit, to show a progression of how I got to where it ended up. If you have any further questions though, let's open up another issue to discuss? I recommend a new issue as I think the other issues are all interconnected and centralizing to one issue will help us keep things straight!
