### ISSUE TITLE
Why is .ConfigureAwait(false) not used?

### ISSUE THREAD

**Issue by escalonn** [dotnet-architecture/eShopOnWeb#311]
Throughout the app's libraries, especially in the AppCore Services, we have `await`s that have no need to resume in the same context afterwards. In such a case is it not best practice to append `.ConfigureAwait(false)`?

As e.g. https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html
"You Don’t Need ConfigureAwait(false) [in ASP.NET Core projects], But Still Use It in Libraries"

**Comment by efleming18** [comment]
Hey @escalonn - correct. In .NET Core apps there's no need to use `.ConfigureAwait(false)`. In the blog post you linked they are talking about reusing the library in a project that may not be running on .NET Core yet. As this entire project is upgraded to .NET Core there's no need for us to use `ConfigureAwait`, but if we had a legacy .NET application that also depended on some of the library projects we would certainly have to take it in to consideration.
