### ISSUE TITLE
Moving to .NET Core 3

### ISSUE THREAD

**Issue by artrs-prog** [dotnet-architecture/eShopOnWeb#313]
Since the latest stable version is 3.0, are there any plans to migrate to it?

**Comment by ardalis** [comment]
Yes, soon.

**Comment by vlyakh** [comment]
Hey guys
Any chance we can get it done in a week?

**Comment by ardalis** [comment]
Likely not but check out https://github.com/ardalis/cleanarchitecture which is upgraded already and can be used as a starting point for new solutions.

**Comment by stevenvolckaert** [comment]
Any update on this? Can we expect the update soon?

**Comment by ardalis** [comment]
Relatively: https://github.com/dotnet-architecture/eShopOnWeb/pull/323

**Comment by efleming18** [comment]
Hey @artrs-prog @stevenvolckaert @vlyakh  - the master branch has been updated to .NET Core 3.0.
Take a look and if you have any questions, please feel free to open up new issues for us to discuss.

**Comment by vlyakh** [comment]
Thanks @efleming18

**Comment by stevenvolckaert** [comment]
Thank you @efleming18!
