### ISSUE TITLE
General EfRepository with a specific DbContext

### ISSUE THREAD

**Issue by schreys** [dotnet-architecture/eShopOnWeb#317]
Would it be possible to make EfRepository more a generic EF repository? It now depends on a specific dbcontext, if I would have 2 specific DbContexts in my solution, I would need to implement this twice?

**Comment by ardalis** [comment]
You could modify it to require an EF Core DbContext, and then specify which EfRepository got which DbContext. You could probably also make it work by defining it like
```
public class EfDbContext<TDbContext> : IRepository
{
   private readonly TDbContext _dbContext;
   public EfDbContext(TDbContext dbContext)
  {
    _dbContext = dbContext;
  }
}
```
I haven't tried it but I suspect something like this would work fine.

**Comment by fingers10** [comment]
> You could modify it to require an EF Core DbContext, and then specify which EfRepository got which DbContext. You could probably also make it work by defining it like
> 
> ```
> public class EfDbContext<TDbContext> : IRepository
> {
>    private readonly TDbContext _dbContext;
>    public EfDbContext(TDbContext dbContext)
>   {
>     _dbContext = dbContext;
>   }
> }
> ```
> 
> I haven't tried it but I suspect something like this would work fine.

doing so throws compile time error at `_dbContext.Set<T>().Add(entity);`

saying,

>`TDbContext` does not contain a definition for 'Entry' and no accessible extension method 'Entry' accepting a first argument of type `TDbContext` could be found (are you missing a using directive or an assembly reference?)

**Comment by fiseni** [comment]
I think ardalis just gave a general idea of how it can be done. If you want to implement to the existing code, you would need something as following. First, you have to define what TDbContext generic parameters means, so the "Set" method could be recognized.
Just keep in mind that entities of each context should inherit the BaseEntity and implement IAggregateRoot (or just modify it to your needs).

I still recommend to keep separate repositories for each context. If not, you will have to be careful how you use the repository. Imagine you instantiate a repository with one dbcontext, and then you use entities of the other dbcontext on it.

```
public class EfRepository<T, TDbContext> : IAsyncRepository<T>
where T : BaseEntity, IAggregateRoot
where TDbContext : DbContext

{
	protected readonly TDbContext _dbContext;

	public EfRepository(TDbContext dbContext)
	{
		_dbContext = dbContext;
	}
	

	public async Task<T> AddAsync(T entity)
	{
		_dbContext.Set<T>().Add(entity);
		await _dbContext.SaveChangesAsync();

		return entity;
	}
}
```

**Comment by schreys** [comment]
I've tried to use the EfRepository<T, TDbContext>, but then the dependency injection fails on this line at runtime:

`services.AddScoped(typeof(IAsyncRepository<>), typeof(EfRepository<,>));`

So I will probably need to add generics toIAsyncRepository to allow an EFRepository but I will need to make an interface for it, meaning I need to interface all methods of EFRepository, which I don't want.

**Comment by fiseni** [comment]
No, you don't need another generic parameter in the interface, since the interface won't utilize that type. The dbcontext is internal concern of the implementation only. Probably you will need something as following.
```
services.AddScoped(typeof(IAsyncRepository<>), typeof(EfRepository<,CatalogContext>));
```
I doubt that this syntax will work. But anyway you will have to define the second parameter somewhere. Otherwise, if you have several contexts, how the the IoC container will know which context to inject.

**Comment by schreys** [comment]
Yes idd, so I guess I will need to 
or.. use generics and use an interface for the methods of DBContext, which I would like to avoid, 
or.. use general DBContext in EFDBContext class, but then I don't have access to the DBSets of the implementation of DBContext of course. I could just return the DBSet using _dbContext.Set<T>() of course.

**Comment by efleming18** [comment]
@schreys anything else you need here on this one?

**Comment by schreys** [comment]
@efleming18 no it's ok for me.
