### ISSUE TITLE
Minor update to vsmac linux container wiki page

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet-architecture/eShopOnWeb#321]
For the wiki page at https://github.com/dotnet-architecture/eShopOnWeb/wiki/03b.-Running-Locally-on-a-Linux-Container-from-Visual-Studio-for-Mac

We should change "Press F5 to run the project or select Debug > Start Debugging from the menu." to "Run the project with `Run`>`Start Debugging` from the menu.

cc @ardalis

**Comment by efleming18** [comment]
Updated @sayedihashimi - thanks!

**Comment by sayedihashimi** [comment]
Thanks
