### ISSUE TITLE
Security Issue: flood DB with basket records.

### ISSUE THREAD

**Issue by fiseni** [dotnet-architecture/eShopOnWeb#329]
If an anonymous user adds item to basket, cookie is created with newly generated Guid, and basket record is created on DB. If the cookie is deleted by the user, and the action is repeated, new record on DB will be created.
This might be a security issue, since malicious script can be written to flood the DB in no time.

I understand that this is just an example project, and I don't know if you want to tackle the possible security issues. But, it might be wise to warn the new users.

**Comment by efleming18** [comment]
Hi @fiseni - thanks for bringing this up. I will take a look in to it and report back to you.

**Comment by efleming18** [comment]
Hey @fiseni - I don't think this warrants being included in the sample but it's a good question so I wanted to share some thoughts on how to prevent it should you want to.

One way to do it would be Rate Limiting. You could use something like [this](https://github.com/stefanprodan/AspNetCoreRateLimit) and rate limit requests by IP, client ID, etc and also limit specific API endpoints, verbs, etc.

You could also clean up anonymous baskets at some regular interval (every 24 hours for example). With more and more applications being hosted in the cloud, scalable databases should be able to handle an influx of baskets and then they would get cleaned up after 24 hours. So, that would help as long as the site isn't being DOSed with all of the requests in the first place.

**Comment by fiseni** [comment]
Hi @efleming18 - Oh it's ok, I understand the scope of the project. I just wanted to bring up this issue, to make the audience aware of the possible scenarios in the real world implementations.

You gave some great tips. But, all of that seem as a workaround to the real problem. In my opinion the real issue is that we're allowing guest users to make persistent changes to our application/infrastructure. And that's the key point, persistent changes. Limiting requests (in any form), might work great for other type of attacks, which have momental and transitive nature, with no persistent consequences (eg. DDos). We should consider that once someone has the power of causing persistent changes, then the attacks can be slow and long lasting.
Cleaning the table periodically is probably the better idea. But, how would you distinct the basket records of legitimite anonymous users and the troublesome ones? If we keep IP records or similar data, then suddenly domain model becomes too aware of the http requests themselves. We should keep domain model agnostic of infrastructural details.

Ideally, if the guest users should have cart, then we let them keep track of it. In an SPA that would be through browser storage, cache.. In an MVC, probably that would be the cookies, we keep whole cart in a cookie, or span through multiple ones.

Anyhow, as I said, my intention was to bring some attention to the subject. Please feel free to close the issue.

Thank you for the discussion.

**Comment by efleming18** [comment]
I definitely agree that a big issue is the persistent changes, but in some cases the persistent changes, may provide strong value to the business to run analytics on. They may want to see how many anonymous carts are being abandoned, what/how many items are in the cart when they are abandoned, etc. If the company would have these analytics in place ahead of time, they would most certainly be able to tell when an anomaly is happening when someone is trying to attack the site. You could even use this data as a way to look in your monitoring tools and potentially find the offending IP and block it at an infrastructure level at that point. 

I would also say that there are other ways to have insight that an attack is occurring. Setting up a monitoring tool like Application Insights would be able to give you information in to the # of API requests you're getting and you likely would have set a baseline at some point as to what you expect. If one day, the application says your API/application has 10x the amount of traffic, it would be a good time to take a look at the application to make sure it's not an attack or if your baseline needs to be adjusted. If you begin investigating and it looks like only one specific scenario is being hit over and over again (via logs, # of requests, etc) then you could take action on an infrastructure level if you needed to. This would be in a scenario where there is business value in keeping around the anonymous baskets / information for 24-48 hours. I think there would be multple ways to help out the application if you needed to persistent the changes. 

If there is no business value around keeping anonymous baskets to run analytics or any other processes on then I agree, keeping them in browser storage, cache, JWT, cookie, etc would be a great alternative.

**Comment by fiseni** [comment]
All the topics u brought up in the post, are completely legitime and meaningful. I agree with all that.
As you implied, prevention might be done through active monitoring too.
Thanks.

**Comment by efleming18** [comment]
Thanks for the great discussion @fiseni ! :)
