### ISSUE TITLE
How to use Nested Includes between context?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#333]
I have a `ApplicationUser` which is loaded using `AppIdentityDbContext`

```c#
public class ApplicationUser : IdentityUser<Guid>
    {
        public ApplicationUser()
        {

        }

        public Guid BranchId { get; set; }
        public Branch Branch { get; set; }
    }
```
```c#
public class AppIdentityDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>
    {
        public AppIdentityDbContext(DbContextOptions<AppIdentityDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.ApplyConfigurationsFromAssembly(typeof(AppIdentityDbContext).Assembly);

            base.OnModelCreating(builder);
            builder.Entity<ApplicationUser>().ToTable("Users", "Account");
        }
    }
```

My `Branch` navigation property in `ApplicationUser` is loaded from `DataContext`

```c#
public class Branch : BaseEntity<Guid>, IAggregateRoot
    {
        private Branch()
        {
            // required by EF
        }

        public Branch()
        {
            
        }

        public Guid ClientId { get; set; }
        public Client Client { get; set; }
    }
```
```c#
public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        {
        }

        public DbSet<Client> Clients { get; set; }
        public DbSet<Branch> Branches { get; set; }
        
    }
```

I'm trying to Include `Branch` with `ApplicationUser` using `UserSpecification`

```c#
public class UserSpecification : BaseSpecification<ApplicationUser>
    {
        public UserSpecification()
        {
            AddInclude(u => u.Branch);
            AddInclude($"{nameof(ApplicationUser.Branch)}.{nameof(Branch.Client)}");
        }
    }
```

when I try to load user with above specification I always get `null` for `Branch` property in `ApplicationUser`

```c#
        var userSpecification = new UserSpecification();
        var userWithBranch = await _userRepository.ListAsync(userSpecification);
``` 

Any helps/suggestions on how to make this work? is this possible? please assist.

**Comment by fiseni** [comment]
You simply can't.
In your case AppIdentityDbContext is not tracking Branch. It's just some object for it, it's not aware that it represents some table in the DB. Since the default value for types is null, it would just return null.

You can try adding DbSets in AppIdentityDbContext as well
```
public DbSet<Client> Clients { get; set; }
public DbSet<Branch> Branches { get; set; }
```

But, I would highly discourage doing that. Different contexts working with the same table is not wise idea at all. Since you have 2 separate contexts, you should apply some strict boundaries around them. Try to refactor your code according to that idea.

**Comment by fingers10** [comment]
@fiseni Thanks for the explanation. Now I understand what is boundary and how to define it. So I first need to fetch user from one context and related entities from another context and I should map them accordingly based on my needs?

**Comment by fiseni** [comment]
Yes, basically that would be the case. You would keep the identity guid as a string in some of your tables. I think something similar is done here in this project, with the buyer entity..

**Comment by fingers10** [comment]
@fiseni Thanks again. I'll look on the buyer entity. I'm good to close this.
