### ISSUE TITLE
Need ConfigureDevelopmentServices to configure for testing

### ISSUE THREAD

**Issue by umarfarooq125** [dotnet-architecture/eShopOnWeb#334]
I am working on **FunctionalTests** project. I tried to run the sample test it calls **ConfigureDevelopmentServices** in the main project startup file where then **Inmemory** database is being used. It seems bit weird that for testing and development same **ConfigureDevelopmentServices** function is called. I actually want to use **inmemory** database only in case of testing not for development. So I feel that there should be **ConfigureTestingServices** method which should be called when I run tests from **FunctionalTestProject**.

**Comment by efleming18** [comment]
Hey @umarfarooq125 - I am in agreement with you. I've been using InMemory databases less and less when it comes to a development environment so having a specific `ConfigureTestingServices` for the Functional Tests to use makes sense to me. Thanks for the call out! I have a PR linked here, and will most likely get it merged shortly.
