### ISSUE TITLE
Add GroupBy and Select implementation in Specification<T> Pattern.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet-architecture/eShopOnWeb#342]
There is no implantation details for the `GroupBy` and `Select` in Specification<T> pattern. Please add this showing how we can get the data based on `GroupBy` using the Specification<T> pattern.

For example how can I build the following equivalent output uisng Specification<T> pattern:

        var empAvgSalary =  _context.Set<Employee>().GroupBy(e => new {e.EmployeeName, e.DepartmentName})
                .Select(group => new
                {
                    EmployeeName = group.Key.EmployeeName,
                    DepartmentName = group.Key.DepartmentName,
                    AvgSalary = group.Average(e => e.Salary)
                }).ToList();

Thank you.

**Comment by efleming18** [comment]
Hey @TanvirArjel - Implementing those would be useful I agree. We may switch to using this NuGet package created by @ardalis (a maintainer on this repo) for the functionality. Before we do that though, here are some links to hopefully help with your questions.

[Specifications Repo](https://github.com/ardalis/Specification)

[GroupBy Implementation](https://github.com/ardalis/Specification/blob/master/src/Ardalis.Specification/BaseSpecification.cs#L32)

[GroupBy Tests](https://github.com/ardalis/Specification/blob/master/tests/Ardalis.Specification.IntegrationTests/DatabaseCommunicationTests.cs#L117)

[Selector Implementation](https://github.com/ardalis/Specification/blob/master/tests/Ardalis.Specification.IntegrationTests/SelectorTests.cs)

[Selector Tests](https://github.com/ardalis/Specification/blob/master/tests/Ardalis.Specification.IntegrationTests/SelectorTests.cs)

Hopefully this helps for now!

**Comment by efleming18** [comment]
I'm going to close this issue as the repo has been updated to use the Ardalis.Specifications NuGet packages linked in the comments above.

**Comment by jamsshhayd** [comment]
Anybody found solution to this? I am trying to add a group by, in Query but it seems there is no method available. Plus, I can pass on an expression in `PostProcessingAction` but I do not want my query to be processed on a List.

**Comment by fiseni** [comment]
There is no support for `GroupBy` for now. Refer to this issue [here](https://github.com/ardalis/Specification/issues/138).
