### ISSUE TITLE
Implementing a Blazor version

### ISSUE THREAD

**Issue by justSteve** [dotnet-architecture/eShopOnWeb#343]
I'm curious about preparing for Blazor's release next spring in terms of implementing it for eShopOnWeb. I'd thought I'd read a post by @ardalis somewhere but I've poked around without finding anything. Has anything addressing this been published? Perhaps we are still too far out from release to do anything really productive - seems there's still work for Core 3.x to be completed. Am generally just interested in find out next steps for the project. thx!

**Comment by punkouter2018** [comment]
I also would like to see a separate webassembly blazor project so see best practices. OR can anyone point me to something similiar ?

**Comment by ardalis** [comment]
There's this: https://github.com/dotnet-architecture/eShopOnBlazor

I'm working on a Blazor WebAssembly implementation for eShopOnWeb presently as well. Should be done very soon / this month.

**Comment by justSteve** [comment]
I've just re-opened the project with current code and see new folders dedicated to Blazor but I'm not seeing any readMe or other form of commentary. Might be worth posting a link for this thread?

**Comment by justSteve** [comment]
Found https://github.com/dotnet-architecture/eShopOnWeb/issues/428

**Comment by ardalis** [comment]
I'll try and add some more updates to the README about it. The eBook is updated with the latest and covers Blazor now, FYI.
