### ISSUE TITLE
Can we add AsNoTracking() in EfRepository<T>?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#346]
Hi All,

All of us know that `.AsNoTracking()` query executes quickly because there is no need to setup change tracking information. It is useful when the results are used in a read-only scenario. 

1. So can we add `.AsNoTracking()` for read operations in `EfRepository<T>` or is there any way to enable this behavior for specific `<T>` repository  if we are sure that data the returned doesn't need to be tracked? for example, getting data to generate reports.
2. Is there any reason why it is not added in this project?

Please share your thoughts on this.

Thanks,
Abdul Rahman

**Comment by ardalis** [comment]
My recommendation if you want to implement this is to have a separate interface, like IReadOnlyRepository<T>, so it's clear from the client when they request the interface what their intention is (if they need readonly or not). The sort of thing isn't in the project currently mainly for reasons of simplicity.

Note that in my experience if you know certain data is read-only and that it's requested often enough to make an impact on overall system performance, you're probably going to get orders of magnitude more performance benefit from adding caching than from worry about AsReadOnly. You can certainly add it, but it does add additional complexity for a very small % improvement in performance.
