### ISSUE TITLE
What design patterns are used in this app  ? 

### ISSUE THREAD

**Issue by punkouter2018** [dotnet-architecture/eShopOnWeb#348]
I am studying design patterns but it would be more helpful to see those applied to an actual solution. Could anyone point out some patterns in the code so I could see real world use of them ?    Or if there is some another application you know of that documents the design patterns in it even better..

**Comment by fingers10** [comment]
As far as I know,

1. Specification Pattern
2. Repository Pattern

**Comment by punkouter2018** [comment]
Yes. I know exactly where those are. But there are so many of the other patterns I would love to see in a sample site.

**Comment by ardalis** [comment]
I could definitely see adding a summary of "Design Patterns used in eShopOnWeb" perhaps to the wiki. Adding to @fingers10  there's also Model-View-Controller (obviously) and Strategy (dependency injection). Also Decorator (CachedService in Web). Like all ASPNET Core apps it uses the Builder pattern that's in Core itself (for configuration and webhostbuilders, for instance). We could enhance one of the test projects with a builder as well as described here: 
https://ardalis.com/improve-tests-with-the-builder-pattern-for-test-data

There are probably a few others I'm forgetting at the moment.

**Comment by punkouter2018** [comment]
The way my brain works is I need to see real world examples to understand things... I have found many articles on design patterns but always hoping someone would create an app as part of the topic that shows how they are used in a real world app.. But for eShop it might be awkward trying to shoehorn a FLYWEIGHT pattern or something in... Strategy = DI ?  I needs to look at cached service closer and decorator pattern

**Comment by fingers10** [comment]
@ardalis MVC is a design pattern or architecture patter? Or both means the same?

**Comment by efleming18** [comment]
MVC would be considered a design pattern @fingers10. I, personally, would shy away from considering design patterns and architecture patterns the same. Design patterns are things like @ardalis listed above, MVC, etc. Architecture is more of way to organize and assemble a specific project/solution/system/service which includes incorporating design patterns.

@punkouter2018 - I think I know what you mean. You see a design pattern, and want to see a real life example of it- I am the same way. But for something like eShop it's difficult to have _many_ different design patterns throughout. It starts to get confusing and can take away from the design patterns you're already using. Definitely take a look for some of the patterns @ardalis called out above and if you have any questions on those, or where to find them, etc just open up another issue for discussion and we'd be happy to talk about it.
