### ISSUE TITLE
order not submitted to the user when NOT pressing 'Update' button 

### ISSUE THREAD

**Issue by AtaaEddin** [dotnet-architecture/eShopOnWeb#352]
I noticed the error following this flow :
   1- (starting without logging in ) Add item to basket.
   2- Change the Quantity number.
   3- Press 'checkout' button without pressing 'Update' button.
   4- Will ask for login, do login.
   5- Go for 'My orders' link and nothing showing there.

**Comment by efleming18** [comment]
Hey @AtaaEddin - thanks for raising this issue. I've confirmed this is happening and will look in to it soon.

**Comment by michelcedric** [comment]
I take a look on that a already almost finished :)

**Comment by michelcedric** [comment]
https://github.com/dotnet-architecture/eShopOnWeb/pull/371
This Pull request fixed this workflow:

1- (starting without logging in ) Add item to basket.
3- Press 'checkout' button without pressing 'Update' button.
4- Will ask for login, do login.
5- Go for 'My orders' link and nothing showing there.
    -->Now the order appear :)

**Comment by efleming18** [comment]
Resolved. Thanks, @michelcedric !
