### ISSUE TITLE
When should I use controllers and when razor pages?

### ISSUE THREAD

**Issue by zn** [dotnet-architecture/eShopOnWeb#353]
Hello everyone! 

I'm learning asp.net core by reading this project. I see that in this project you have both controllers and razor pages. 
Firstly, let's take a look at controllers:  ManageController has a lot of code (500 lines), but OrderController has less than 50 lines, because of MediatR. My first question is why you didn't realize ManageController with Mediatr?
And my second question is why do you have both razor pages and controllers in one project? Isn't it better to do all in one style? Why did you realize, for example Admin as a razor page but not as a controller? And vice versa, why wouldn't make OrderController a razor page?

PS: sorry if i made any grammatical errors

**Comment by efleming18** [comment]
Hey @zn - good question! 

With this being a demo app, we were trying to show a few different ways to approach solutions. For example. like you pointed out the OrderController was updated to use MediatR while ManageController was not so you can see the advantages / disadvantages to each while in the same repo. 

The same applies to razor pages vs MVC. We could do it one way or the other, but we're trying to show how it's done in each. A few years ago in this project we tried to maintain two separate projects - 1 for just MVC and 1 for just Razor pages. It was difficult to maintain both, so we combined the projects.

Hopefully that helps!

**Comment by zn** [comment]
@efleming18 Thanks for the explanation! It explains everything
