### ISSUE TITLE
 .epub or .mobi format for ASP.NET Core 3.1

### ISSUE THREAD

**Issue by vulcanlee** [dotnet-architecture/eShopOnWeb#354]
Whether has the ASP.NET Core 3.1 version of Architecting Modern Web Applications with ASP.NET Core and Azure for .epub or .mobi?

**Comment by epikkoder** [comment]
I second this. I'm also looking for the latest ebook version.

**Comment by ardalis** [comment]
We currently are not planning on publishing in these formats going forward due to lack of interest (despite this issue, there weren't significant downloads in these formats). Sorry.
