### ISSUE TITLE
Example for IAsyncEnumerable<T>

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#355]
Dear Team,

Is there any chance we can use IAsyncEnumerable<T> feature in this project? Any example usecase? Just curious to know.

Thanks,
Abdul Rahman

**Comment by efleming18** [comment]
Hey @fingers10 - is there in place you could see us using this in the project? For me, nothing is coming to mind. If this were a larger application with customers having hundreds of orders I could _potentially_ see using it to build the list/update the UI as the list of orders was retrieved from the database.

If you're looking for an example, the docs have a tutorial of using it [here](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream).

**Comment by efleming18** [comment]
@fingers10 - I'm going to close this issue as I don't see a place we should really leverage it here yet. Please let me know if you see a place though. Hopefully the example from the docs I provided helps!
