### ISSUE TITLE
How Coupled is this Solution to the UI?

### ISSUE THREAD

**Issue by iammukeshm** [dotnet-architecture/eShopOnWeb#356]
Using this approach, will I be able to add additional UI Projects ( Angular/ React.js) to consume the API of  eShopOnWeb.Web? I would like to keep the Authentication on the eshop layer itself . Could anyone give a quick insight about this! TIA

**Comment by punkouter2018** [comment]
As I understand it. It is a RAZOR project that has pages but also has controllers that can be access by SPAs. Would it ever make sense for the code behind in the pages to call the controllers? If you were using both a SPA and a RAZOR project?  Or make sense to split the WEB API into a separate project?

**Comment by ardalis** [comment]
I don't think as written currently it exposes enough APIs to be able to duplicate 100% of the functionality in a different SPA UI. You would just need to add additional APIs for any missing functionality you needed.

**Comment by iammukeshm** [comment]
@ardalis Hi, so you mean it's still possible to use this Solution as both API and MVC UI without actually seperating the API part to a different project? How about the authentication of the API? A simple postman call to a secured API endpoint would return me the HTML of the Login page and a 200 ok Status code? Is there a way to secure the API in a better way that shows 401s? And how about the Security Tokens if i add another UI CLIENT, let's say React.js? Who would be responsible for authenticating, registering users?

**Comment by ardalis** [comment]
Possible, yes. And if the only client for the APIs is a SPA that's dedicated to this app, then that might be fine. If you're looking to publish more general-purpose APIs that might be called by public consumers or other services in your organization then it probably makes sense to split them into another project. Securing them is another whole topic. My recommendation is to use tokens and I've had good luck with IdentityServer4 as a (probably separate) token server. You can configure everything in one project (ASP.NET Core Razor Pages or Views, static SPA, ASP.NET Core API endpoints, and IdentityServer4) but you may find it's easier if you think about splitting them up. If nothing else, hosting IdentityServer separately would let you use it to secure multiple different resources more easily. Does that help?

**Comment by efleming18** [comment]
Hey @iammukeshm - just checking in if @ardalis's answer helped you out or if you're looking for some more information?
