### ISSUE TITLE
Generic Context in EFRepository

### ISSUE THREAD

**Issue by ardianreqica** [dotnet-architecture/eShopOnWeb#357]
I have multilple DBContext and want to use the same EfRepository to query data.

I have changed EFRepository constructor and now as parameter is DBContext.

readonly DbContext _dbContext;

EfRepository(DbContext dbContext)
{
            _dbContext = dbContext;
}

When as parameter is specific context it is working but I want to use the same EFRepository.

I added in startup dependencies
            
services.AddScoped(
                typeof(IRepository<DeclarationForm>),
                typeof(EfRepository<DeclarationForm>)
                );

The problem is when as context is DBContext I am getting error:
 
InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContext' while attempting to activate 'Infrastructure.Data.EfRepository`1[DeclarationForm]'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)       

I tried to specify Context in Startup as follows but I am getting syntax error.

            //services.AddScoped(
            //    typeof(IRepository<DeclarationForm>),
            //    typeof(EfRepository<DeclarationForm>(new TestContext()))
            //    );

**Comment by efleming18** [comment]
Hey @ardianreqica - do you have this in a branch somewhere I can take a look at? In this project we have multiple DBContext's but they are not sharing the EFRepository.

Take a look at the [OrderRepository](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/OrderRepository.cs). We pass in the CatalogContext to this, and the generic, EFRepository, also takes in the DBContext as a parameter in the constructor. 

The two DBContexts are both set up from the [Startup](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Startup.cs#L52).

Does that help? I would check out how we're doing it with something like the OrderRepository to see if it helps get you moving in the right direction?

**Comment by michelcedric** [comment]
Hi
Don't foget to add the bothcontext :
services.AddDbContext
and add each repository :
 services.AddScoped<IOrderRepository, OrderRepository>();
If you have some issue don't hesitate to share the link of your repository.

**Comment by efleming18** [comment]
Hey @ardianreqica - Hopefully you find this useful. I'm going to close this issue, but if you have any further questions feel free to open us another issue and if you can, provide a link to a branch or a repository to look at so I can help you better. Thanks!
