### ISSUE TITLE
CreateIdentityIfNotCreated - Why is this necessary?

### ISSUE THREAD

**Issue by yncardoso** [dotnet-architecture/eShopOnWeb#359]
Hi guys,

Not a bug, more like a question. I've noticed that this method was created because you're using _UserManager_ inside _WebTestFixture_. I've come across the same thing, and for some reason it doesn't feel "right". Is there any way to achive the same without adding that method? Thanks.

**Comment by efleming18** [comment]
Hey @yncardoso - good question! That method is no longer needed. I believe it was left over from some earlier refactorings that were being done. There's a PR linked to this here to remove it.
