### ISSUE TITLE
Aren't "features" belonging to core?

### ISSUE THREAD

**Issue by kiske1** [dotnet-architecture/eShopOnWeb#365]
Hello,

The OrderController makes use of mediatr to query the repository via features. But the "features" in which the queries agains the repo are implemented in the Web project. 
Shouldn't the feature's being implemented into the core, as they are just like, well... CQRS queries?

**Comment by efleming18** [comment]
Hey @kiske1 - good question. So the "Features" folder in the Web project are a way of organizing the web project to make use of MediatR. This is to mean more of "features" that the web project exposes but their implementation and business logic are still done in Core. In our example, one feature is that we can return orders for a logged in user. The implementation of all of this though is still done in Application Core. So the only call that "does" anything is the call to retrieve the orders.
`var orders = await _orderRepository.ListAsync(specification);`

This leverages the IOrderRepository which is exposed via the Core project. The Core project is still doing the actual work of knowing how to retrieve the orders and return them back. The logic that is in the MedaitR handler is logic that could normally have to be in a controller. Now that we can leverage MediatR to pull this logic out, our controllers are almost empty besides having to deal with what to return to the Views - which makes us adhere to SRP more closely.

Does this help?

**Comment by efleming18** [comment]
Hey @kiske1 - I'm going to close this issue. If you have further questions, please let me know!

**Comment by justSteve** [comment]
I found the explanation very helpful -- thanks for the thoroughness.
