### ISSUE TITLE
Function and use of the Query helpers in ApplicationCore

### ISSUE THREAD

**Issue by ThiboTouch** [dotnet-architecture/eShopOnWeb#368]
Not sure if this is the right place to post about an explanation but I'd like to know about how and where in the application are the files under ApplicationCore/Helpers/Query used? I've been studying the code base and this is one area I'm having a difficulty of understanding its purpose. An explanation would be awesome.

**Comment by michelcedric** [comment]
Hi @ThiboTouch 
This folder contains A IncludeQueryExtensions.
 - This one contains the logical to manipulate the include query of the Specification Pattern.
The BaseSpecification have a AddIncludes mehtod it use a Func of IncludeAggregator. You can find a usage of this in CustomerOrdersWithItemsSpecification.
The CustomerOrdersWithItemsSpecification is evaluate by SpecificationEvaluator during the call one a method in the repository.
This include is necessary for Enity Framework to specified with child of the root object you want to load.
