### ISSUE TITLE
FirstOrDefault at Database level using specification pattern

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#369]
I'm following the Specification Pattern used in this project. However I can see that I'm not able to apply `FirstOrDefault()` at the database level.

Example,
I have a table with event details and I need to fetch the next upcoming event. With the Specification Pattern I can able to `OrderBy()` event date in ascending order and apply `Where()` to filter events with `Date > DateTime.Now.Date`. But this will give a list of upcoming events and I need to make a `FirstOrDefault()` on client side. Is there any way to make this happen at database level using specification pattern?

**Specification:**
```c#
public class UpcomingEventSpecification : BaseSpecification<Event>
{
    public UpcomingEventSpecification() : base(e => e.Date > DateTimeOffset.Now)
    {
        ApplyOrderBy(x => x.Date);
    }
}
```  

Code:
```c#
var specification = new UpcomingEventSpecification();

var @event = (await _eventRepository.ListAsync(specification)).FirstOrDefault();
```

After googling I found that the following [link shows ways to implement multiple specification to an entity](https://gunnarpeipman.com/ef-core-query-specification/). Can this be implemented in eshoponweb?

Please assist on how to improve this pattern and this can be added to eshoponweb project as well for reference.

Thanks,
fingers10

**Comment by michelcedric** [comment]
@fingers10 
I create a pull request to add the support of the first and FirstOrDefault directly in the repository.
You can now create a specification with your order by (ApplyOrderBy)
And after that call the new method in repository
var @event = await _eventRepository.FirstOrDefaultAsync(specification);

https://github.com/dotnet-architecture/eShopOnWeb/pull/370/files

**Comment by fingers10** [comment]
@michelcedric That works as excepted. Many Thanks.
