### ISSUE TITLE
How to chain/add multiple specifications?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#372]
Is it possible to chain/add multiple specifications to retrieve data? Can the Specification Pattern implementation in this project be improved? Please assist with the possibilities.

**Comment by michelcedric** [comment]
Hi @fingers10 
If you want chain/multiple filter, you must create a new specification call as 
https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Specifications/CustomerOrdersWithItemsSpecification.cs
In this case, it adds a filter on the BuyerId, and add include to load child data
You are free to add(line 11) multiple filter, add order,...
It's necessesary to have one specification class by call to the repository. That keep one query to your database.

**Comment by efleming18** [comment]
Hey @fingers10 - like @michelcedric is saying, yes it is possible to chain them together like the example he provided. In the future, we may update the Specification Pattern implementation to just use @ardalis' [Specification repository](https://github.com/ardalis/Specification) as it has a few more implementations than we do currently. 

Any further questions on this one?

**Comment by fingers10** [comment]
No. I'm good at the moment. Thanks @michelcedric  and @efleming18 .
