### ISSUE TITLE
Add devcontainer/extension files

### ISSUE THREAD

**Issue by timheuer** [dotnet-architecture/eShopOnWeb#375]
For VS Codespaces add devcontainer and extensions files for better experiences.

**Comment by efleming18** [comment]
@timheuer - can I close this issue now? Seems like it was resolved with the merge of PR: https://github.com/dotnet-architecture/eShopOnWeb/pull/376

**Comment by timheuer** [comment]
Yes, not sure why the merge didn't auto-close.
