### ISSUE TITLE
No database provider after dotnet-ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj

### ISSUE THREAD

**Issue by jackwrx** [dotnet-architecture/eShopOnWeb#377]
at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

**Comment by michelcedric** [comment]
Hi @jackwrx 
You propably forget to change the InMemoryDatabase:

Configuring the sample to use SQL Server
Update Startup.cs's ConfigureDevelopmentServices method as follows:
 public void ConfigureDevelopmentServices(IServiceCollection services)
        {
            // use in-memory database
            //ConfigureTestingServices(services);

            // use real database
            ConfigureProductionServices(services);

        }

**Comment by efleming18** [comment]
Hey @jackwrx - I agree with what @michelcedric is proposing to try first. If that doesn't fix your issue, please let me know.

**Comment by jackwrx** [comment]
@all thanks for the reply, after I changed to real database, this is the error:

System.InvalidOperationException: The DbContextOptions passed to the CatalogContext constructor must be a DbContextOptions<CatalogContext>. When registering multiple DbContext types make sure that the constructor for each context type has a DbContextOptions<TContext> parameter rather than a non-generic DbContextOptions parameter.

**Comment by michelcedric** [comment]
Hi @jackwrx 
It's really strange. I just check on the master Branch (Pull master) put in comment 
'''
 //ConfigureInMemoryDatabases(services);
'''
And let only this one
'''
 ConfigureProductionServices(services);
'''
And it's working, you maybe change other things?

**Comment by efleming18** [comment]
@jackwrx I've also tried it again locally from the master branch and it's working for me. Can you 

- Confirm you're on the master branch and don't have any outstanding changes on the branch? 
- Make sure your connection string is valid to connect to a local instance running on your machine?
- Make sure you're running the command from the Web directory

**Comment by jackwrx** [comment]
Hi, I have re-pull the master branch and manage to get it to run locally. Thanks all!

**Comment by jackwrx** [comment]
Thank you for all the suggestion and work.
