### ISSUE TITLE
Orderby, ThenBy

### ISSUE THREAD

**Issue by klides** [dotnet-architecture/eShopOnWeb#380]
Hi, do you will implement "ThenBy" sorting? Regards!

**Comment by efleming18** [comment]
Hey @klides - I have a PR out now: https://github.com/dotnet-architecture/eShopOnWeb/pull/389 that is updating this repo to use the [Ardalis.Specifications](https://github.com/ardalis/Specification) NuGet repo. This is where I implemented an OrderBy, ThenBy Example. You can see the implementation in that repo. 

You can start [here](https://github.com/ardalis/Specification/blob/master/src/Ardalis.Specification/SpecificationEvaluator.cs#L23).

If you have any further questions, let me know.
