### ISSUE TITLE
Devcontainer config is broken

### ISSUE THREAD

**Issue by ankitbko** [dotnet-architecture/eShopOnWeb#382]
Follow up on #375 

@timheuer  when opening it in VS codespace get below error - 
![image](https://user-images.githubusercontent.com/3169316/83024952-763eb080-a04c-11ea-85e8-82422dc9d6e6.png)

The extension has been renamed to `ms-dotnettools.csharp`.

Also `docker-compose` is not available in  base Oryx image. `dotnet-ef` is also not installed. Typically a development environment should have everything configured and installed.

**Comment by ankitbko** [comment]
Also I am unable to connect to the running application on codespace (missing forwardPorts?)

**Comment by timheuer** [comment]
Good catch @ankitbko I'll submit a change for the extension...

I'm able to get the running application working for me in Codespaces.

**Comment by ankitbko** [comment]
Weird why its not working for me in codespace.
Another issue I face is that opening the repo locally in vscode will prompt me to open it in container (as the remote-container extension will find the devcontainer.json). Upon clinking the prompt the launch will fail and close the open folder.

![image](https://user-images.githubusercontent.com/3169316/83063354-9dfa3c80-a07d-11ea-8463-46bb6a0b9ff2.png)

This is because the devcontainer config is not actually valid to run it locally. Should we just create a valid devcontainer along with its own dockerfile?

**Comment by ankitbko** [comment]
You know what, I was thinking of using this repo for a demo so might as well do it properly. I can take this up and create a proper devcontainer setup.
