### ISSUE TITLE
How is the address value object added to the ORDER table and not a separate table?

### ISSUE THREAD

**Issue by punkouter2018** [dotnet-architecture/eShopOnWeb#390]
I am trying to do something similar but it put ADDRESS in a separate table and add underscores. Do I need to hand code the migration files or something ?  My version just creates a separate table for the ADDRESS.

**Comment by ardalis** [comment]
Look into owned entities in ef core.
https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities

The key line is here:
https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/Config/OrderConfiguration.cs#L15

**Comment by efleming18** [comment]
@punkouter2018 Can you post the full EF Configuration you have for where you are are trying to map it in to the same table as another entity? Maybe there is something else missing from the existing configuration. I was going to link to the same places @ardalis is already linking for an example.

**Comment by punkouter2018** [comment]
figured it out.. these two lines were switched around 

`  protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
        }
`

**Comment by punkouter2018** [comment]
and then spent another 3 hours realizing that for whatever reason you cannot use the value object in 2 different entities at the same time with this code..
`  builder.OwnsOne(o => o.ShipToAddress, a =>
            {
                a.WithOwner();


What if I want to use the Address value object it two entities?   What do I change there?  The eshoponweb only uses it on one. `

**Comment by punkouter2018** [comment]
its gotten stranger.. It only seems to work if  I have an unrelated entity with a config that uses the builder.OwnsOne.. Im really confused now.. The structure is right now but I have this dummy object I must keep or it doesn't work
