### ISSUE TITLE
Any vs AnyAsync

### ISSUE THREAD

**Issue by yigith** [dotnet-architecture/eShopOnWeb#396]
Hello, I have a question about the seed method in CatalogContextSeed.

Is there a specific reason for not using 
`if (!await catalogContext.CatalogBrands.AnyAsync()) `
instead of 
`if (!catalogContext.CatalogBrands.Any())`

https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/CatalogContextSeed.cs

**Comment by ardalis** [comment]
It could probably use `AnyAsync`. It's only used for local development/testing in any case but it's a good callout. Do you want to submit a PR?

**Comment by yigith** [comment]
Sure, I would like to submit a PR :)

**Comment by efleming18** [comment]
Resolved by https://github.com/dotnet-architecture/eShopOnWeb/pull/397
