### ISSUE TITLE
AddRange vs AddRangeAsync (Considering HiLo)

### ISSUE THREAD

**Issue by yigith** [dotnet-architecture/eShopOnWeb#398]
> I removed the unused `System.Linq` using statement. Thanks for the contribution @yigith !

You are welcome :) It was a pleasure. I am showing and explaining this project to my students. I want to thank you all for this instructional project.

I just want to ask an additional question related to async methods in the Seed method. 

Do you think 
`catalogContext.CatalogBrands.AddRange(GetPreconfiguredCatalogBrands());`
should be replaced by
`await catalogContext.CatalogBrands.AddRangeAsync(GetPreconfiguredCatalogBrands());`
?

This project uses HiLo as an id generation strategy and the summary of AddRangeAsync method is like the following: 

>         //
>         // Summary:
>         //     Begins tracking the given entities, and any other reachable entities that are
>         //     not already being tracked, in the Microsoft.EntityFrameworkCore.EntityState.Added
>         //     state such that they will be inserted into the database when Microsoft.EntityFrameworkCore.DbContext.SaveChanges
>         //     is called.
>         //     This method is async only to allow special value generators, such as the one
>         //     used by 'Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy.SequenceHiLo',
>         //     to access the database asynchronously. For all other cases the non async method
>         //     should be used.
>         //
>         // Parameters:
>         //   entities:
>         //     The entities to add.
>         //
>         //   cancellationToken:
>         //     A System.Threading.CancellationToken to observe while waiting for the task to
>         //     complete.
>         //
>         // Returns:
>         //     A task that represents the asynchronous operation.
>         public virtual Task AddRangeAsync([NotNullAttribute] IEnumerable<TEntity> entities, CancellationToken cancellationToken = default);

_Originally posted by @yigith in https://github.com/dotnet-architecture/eShopOnWeb/pull/397#issuecomment-644330924_

**Comment by efleming18** [comment]
Thanks @yigith - after doing some further research on it, I do believe changing it to `AddRangeAsync` would be the recommended approach. Would you like to open a PR for this one as well? If not, I'm happy to do it!

**Comment by yigith** [comment]
You are welcome @efleming18, happy to contribute. I've opened a PR.
