### ISSUE TITLE
AddItemToBasket: FirstAsync vs GetByIdAsync

### ISSUE THREAD

**Issue by yigith** [dotnet-architecture/eShopOnWeb#402]
On the class "https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Services/BasketService.cs"

In the method "AddItemToBasket"

I think 
`var basket = await _basketRepository.GetByIdAsync(basketId);`
should be replaced by something like this:
`var basket = await _basketRepository.FirstAsync(new BasketWithItemsSpecification(basketId));`

If we use getbyidasync method, the items navigation property will be -normally- null and 
`basket.AddItem(catalogItemId, price, quantity);`
depends on items being not null.

The website right now works properly because this navigation property is filled by another ef request in the ui layer. However, this method is located in application core layer and shouldn't be dependent on how things are in ui layer.

(Sorry for my english, i hope it makes sense)

**Comment by ardalis** [comment]
Good catch! I agree, we should address this. Do you want to submit another PR?

**Comment by yigith** [comment]
Sure, I would like to submit another PR.

**Comment by efleming18** [comment]
Resolved by attached PR. Thanks @yigith !
