### ISSUE TITLE
Why the Web project should have access to Basket Repository?

### ISSUE THREAD

**Issue by rakesha** [dotnet-architecture/eShopOnWeb#407]
Hi @ardalis, I am new to Clean Architecture, I was wondering why the Web project should have access to Basket Repository? By giving access to the repository in both Web and Core project we don't have clear separation of concerns. Also what if we need to check something for that user before showing him the Basket. It seems like business logic.

**Comment by ardalis** [comment]
Ideally a Repository shouldn't have business logic, per se. It should only be responsible for getting or storing an entity or aggregate from/to persistence. Whatever that might be. If the web project wants to work with the domain model, it needs a way to get those items. If it's not just creating them from scratch, there must be some abstraction it uses to access them from persistence. That abstraction is the Repository pattern. Many applications prefer to decouple the UI/Web project from the domain model via a collection of application services, and that's fine, too. But then these application services still must have a way to access the model from persistence. Does that help?

**Comment by rakesha** [comment]
Yes, @ardalis, and thanks for your reply.
