### ISSUE TITLE
[Request] Idea to help more developers understand clean architecture

### ISSUE THREAD

**Issue by Youssef1313** [dotnet-architecture/eShopOnWeb#415]
Developers with less experience (like me, and many others) that got used to the normal all-in-one code where they just have 4 folders (Models, ViewModels, Views, and Controllers) will see the clean architecture very hard to understand and implement.

I think having an application (Not necessarily the same eShop app) with the ordinal structure and refactoring it to clean architecture step by step in a stream/video will help much much more developers.

I hope you, or someone who want to help, can do this.

**Comment by fiseni** [comment]
My advise would be just keep coding.
Patterns are nothing else than just a common knowledge of the community for some known problems. Principles and architectures are just the same in more generalized form, they address collection of issues.. u could imagine as they address the highway issues in the traffic..
By my experience, in the beginings maybe its important to face the issues or discover the issues by yourself. Once your existing way of doing stuff starts to create problems, once you find yourself in dead end, thats the moment when you'll realize the true value of the mentioned architectures.

But, yea its nice to watch somebody explaining the process in more detail. There are great content out there (i wont post links here). @ardalis also have great content, he could refer some of his content.
Just dont forget to try and feel the pain by yourself :)

**Comment by Youssef1313** [comment]
@fiseni, Thanks. I made small applications already and faced maintainability issues because of bad design/architecture. But for the lack of experience (still student with zero professional experience), I couldn't get to understand the architecture well. As you mentioned, watching someone doing this in more details will help much, not only me, but anyone who is just starting to move towards a clean architecture. Watching doing so starting with a the classical all-in-one will be even better than starting building from scratch. That will give a room for more explanation and comparison.

I hope @ardalis has time to do such a stream/video, or anyone else :)

**Comment by Youssef1313** [comment]
@fiseni, I decided to get my hands dirty and just start to transform a [small & incomplete project](https://GitHub.com/Youssef1313/AskQ) of mine. I've a question, and a personal request:

1. The question: The project is an ask.fm clone, I've two Models, "Question", and "Reply". From my understanding, these should be moved to a separate "Core" project instead of being in "Web". However, the question has a property of type "IdentityUser" which is asp-identity specific thing. How can I address that issue? It's not good for the "Core" project to depend on asp-specific things. I can make an "ApplicationUser" class in the infrastructure, but still the same problem, "Core" will depend on "Infrastructure".

2. The personal request: As I'm refactoring this small project, I'll do that in a small steps, each in a PR. Would you mind reviewing the steps I'll take and point me towards the right direction?

**Comment by fiseni** [comment]
Hey @Youssef1313 ,

I'll try to be of help, of course. 
Your model shouldnt have properties of type "IdentityUser", you would want to store only Guid of the user. Besides that, in real life scenario where I'd have only couple of models, I wouldnt even bother to set up some fancy infrastructure. It would be a classical example of over engineering. But, as an example yea we can do it.

Since this has nothing to do with this project, I'll continue there, not to pollute the space here.

**Comment by kims07231992** [comment]
@Youssef1313  Well, this article is well explaining about the "clean architecture" we are saying here, not the traditional architecture such as MVC.

https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#clean-architecture

**Comment by ardalis** [comment]
Hi @Youssef1313,

It's a good idea I think to show how to refactor from "File - New Project" single app to a multi-project solution. Here is a presentation I gave a few months ago on Clean Architecture that lays out the principles and compares it to other N-Tier architecture approaches (but not really a single project approach): https://www.youtube.com/watch?v=tYoqmL6e4oY

I could probably do a stream on Twitch to cover what you're looking for, though, and then post it to YouTube afterward and maybe link to it from this repo. My twitch is at https://twitch.tv/ardalis if you want to follow so you'll get notified when I'm live (and then you can ask questions live, too).

@kims07231992 good link - that's actually part of the eBook referenced in this project's README. Definitely have a read of that chapter as well as the whole book.

**Comment by Youssef1313** [comment]
@ardalis Thanks for response. I'd love to see this stream very soon :heart:

I'll also give a look to the video you linked to.

**Comment by johnpankowicz** [comment]
I'm also unsure about where to start learning. I don't know whether to focus on the eShopWeb project or Steve's repo. For example, the eShopWeb project's EfRepository.cs is implemented as so:
```
    public class EfRepository<T> : IAsyncRepository<T> where T : BaseEntity, IAggregateRoot
    {
        protected readonly CatalogContext _dbContext;

        public EfRepository(CatalogContext dbContext)
        {
            _dbContext = dbContext;
        }

…
        private IQueryable<T> ApplySpecification(ISpecification<T> spec)
        {
            var evaluator = new SpecificationEvaluator<T>();
            return evaluator.GetQuery(_dbContext.Set<T>().AsQueryable(), spec);
        }
```
The code for this in ardalis/specification is:
```
    public class EfRepository<T> where T : class, IEntity<int>
    {
        protected readonly SampleDbContext _dbContext;
        private readonly ISpecificationEvaluator<T> specificationEvaluator;

        public EfRepository(SampleDbContext dbContext)
        {
            _dbContext = dbContext;
            this.specificationEvaluator = new SpecificationEvaluator<T>();
        }
…
        private IQueryable<T> ApplySpecification(ISpecification<T> specification)
        {
            return specificationEvaluator.GetQuery(_dbContext.Set<T>().AsQueryable(), specification);
        }
```
If I assume that I should work with the latest in ardalis/specification, I then don't have a working sample to go by for integrating this into my .net core app.
Is there any plan for documentation that specifically targets using the NuGet package in an existing (or new) project?

**Comment by ardalis** [comment]
That EfRepository in the Specification repository is just an example; you can implement your own or use that one. This example uses a (slightly) different one and works fine, too.

The ebook is more about fundamentals and principles, not a step-by-step walkthrough of the code itself. I agree that training material would be helpful, although it would become out of date more quickly as the app is updated to new versions of .NET. I'll try and use my stream tomorrow to walk through the eShopOnWeb app. Feel free to join around 12-2pm EDT on twitch.tv/ardalis, or I'll follow up here with a link to the recording afterward. Thanks!

**Comment by ardalis** [comment]
BTW if you want something today here are a few places to start:
https://www.youtube.com/results?search_query=clean+architecture+ardalis

**Comment by johnpankowicz** [comment]
Thanks. I've watched the above video already. I will tune in tomorrow.
But is the code in the latest NuGet package supposed to be the best approach to use? And might eShopWeb be upgraded eventually to use the latest Nuget package?
