### ISSUE TITLE
[Question] Why JsonExtensions belong to ApplicationCore

### ISSUE THREAD

**Issue by Youssef1313** [dotnet-architecture/eShopOnWeb#416]
Why it doesn't belong to Web for example?

**Comment by ardalis** [comment]
It has no dependencies on Web so putting it in Core makes it easier to unit test. It can be used from anywhere there, so if it's needed for consuming a web API via the Infrastructure project, for instance, it's available to be used for that.

**Comment by Youssef1313** [comment]
Thanks. Got it.
