### ISSUE TITLE
Update eBook with Blazor WebAssembly Content

### ISSUE THREAD

**Issue by ardalis** [dotnet-architecture/eShopOnWeb#428]
Cover WebAssembly here:
https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/choose-between-traditional-web-and-single-page-apps

Add coverage of including Blazor Webassembly in the main ASP.NET chapter here:
https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/develop-asp-net-core-mvc-apps
(or add a new chapter)

Things to include

- Project structure
- Blazor server vs. WebAssembly
- Getting data to Blazor
- Shared classes between Blazor client and server
- Security/Auth between server and client
- Reference Blazor eBook (for web forms) https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/

**Comment by punkouter2018** [comment]
How do I start the blazor project?  I can't run it alone.. I tried multiple startups (publicapi and webassembly project) and that didnt work.

**Comment by ShadyNagy** [comment]
@punkouter2018 
- Start PublicApi without debugging.
- Change file Constants in BlazorAdmin  
```
public const string API_URL = "https://localhost:5099/api/"; 
```
to
``` 
public const string API_URL = "https://localhost:44339/api/";
```
- Start Web project.
- Login with admin@microsoft.com in the login page.
- Click in user on the top then click ADMIN link.

**Comment by ShadyNagy** [comment]
@punkouter2018 Kindly you check that [Running the sample](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/README.md#running-the-sample)

**Comment by punkouter2018** [comment]
Where is this line?  I can't find it

public const string API_URL = "https://localhost:5099/api/";

**Comment by ShadyNagy** [comment]
This changed in the last few days, any way you need to run PublicApi and Web.
If you need to change the setting you will find it here appsettings.json, appsettings.Development.json and, appsettings.Docker.json depends on your environment.

> 
> 
> Where is this line? I can't find it
> 
> public const string API_URL = "https://localhost:5099/api/";

**Comment by ardalis** [comment]
WebAssembly is covered in the eBook; closing.
