### ISSUE TITLE
Support Uploading Images for Admin Create Product dialog

### ISSUE THREAD

**Issue by ardalis** [dotnet-architecture/eShopOnWeb#432]
Currently creating new products doesn't support image upload.

Add support for uploading png images.

Nice to have features:
- Resize the image (if necessary) to match others
- Validate the file is an image and reject other extensions/formats
- Limit file size to 500kb
- Name file based on product ID just as others are named
- Place uploaded files in appropriate folder

![image](https://user-images.githubusercontent.com/782127/88546648-b093e200-cfea-11ea-902c-931f4ff6f2ed.png)

**Comment by ShadyNagy** [comment]
> 
>     * Place uploaded files in appropriate folder
@ardalis 
So we need Blazor to send the image to PublicApi and then PublicApi send the image to Web?
Or we need Blazor to send the image directly to Web?

**Comment by ardalis** [comment]
Good question. What do you think makes sense?

I think in a "real" application the images would be in some kind of CDN or abstracted file system, not just in the web's file system. As such, I think PublicApi could have an IFileSystem abstraction it would use to store the images. These could be stored in Azure BlobStorage or S3 or any number of places. It *could* even use an endpoint on Web to push the images there.

If we're running just on localhost, it could just use the actual file system and (assuming a standard side-by-side arrangement of the projects) move the file correctly from /src/PublicApi/upload to /src/Web/wwwroot/images/products.

But if it's running in Docker this probably won't work. At that point you could do some kind of folder mapping in Docker/Docker Compose, or you could have an HTTP endpoint that's used, or some other mechanism.

**Comment by ShadyNagy** [comment]
@ardalis what do you think about that scenario?

we will have endpoint in public api to load images and endpoint to upload the image and then we will use load endpoint in both Web and Balzor also it will work in Docker without any changes and images will be in one place which is public api.

**Comment by ardalis** [comment]
One problem we have here is that, by introducing PublicApi as a separate project, we're no longer strictly a "monolith" as the project was initially. This means we now need to consider ways for separate applications to communicate with one another.

**Comment by ardalis** [comment]
Done, except resizing.
