### ISSUE TITLE
Library cannot be resolved

### ISSUE THREAD

**Issue by abridgel** [dotnet-architecture/eShopOnWeb#439]
After the latest commit this morning my project isn't building

##[error]libman.json(0,0): Error LIB002: The "bootstrap@3.3.7" library could not be resolved by the "unpkg" provider

Lots of errors like these

**Comment by ardalis** [comment]
These are common but intermittent errors. I believe they're fixed in my development branch which I hope to merge today or tomorrow.

**Comment by ardalis** [comment]
Try updating to the latest code from master and see if you still get the issue.

**Comment by abridgel** [comment]
Thanks Steve - I don't see the errors this morning - should we close this?

**Comment by ardalis** [comment]
Yep, thanks!
