### ISSUE TITLE
The functional tests use a shared dbcontext instance

### ISSUE THREAD

**Issue by ThiboTouch** [dotnet-architecture/eShopOnWeb#447]
I've recently ran into a test that accessed an item that's been deleted by the previous test case on the tests: [GetByIdEndpoint.cs](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/tests/FunctionalTests/PublicApi/CatalogItemEndpoints/GetByIdEndpoint.cs)

☝This test gets called after 👉 [DeleteEndpoint.cs](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/tests/FunctionalTests/PublicApi/CatalogItemEndpoints/DeleteEndpoint.cs).

Example: Deleting an item of id 3 and then calling getbyid of 3 fails. It fails because it seems to be using the same dbcontext even though its recreated on every test fixture. Run all the tests as they are ordered alphabetically, the delete test gets called before the getbyid and accessing the same item (using the same id) results in a failed test case.

**Comment by fiseni** [comment]
This is not about using the same `dbContext` per se, but using the same database, and persisting changes.
There are two options to handle the cases where you have tests that update and save some data:
- Create and seed db for each test that mutates persisted data. 
- Get a bit creative and reset the state after each test. You can try this [Nuget package](https://github.com/jbogard/Respawn) for that
