### ISSUE TITLE
CatalogItem properties CatalogType and CatalogBrand never get set?

### ISSUE THREAD

**Issue by storms-lab** [dotnet-architecture/eShopOnWeb#449]
Maybe I just don't understand something that is going on behind the scenes, but do the CatalogType and CatalogBrand properties of CatalogItem never get set? Their corresponding int Ids do (CatalogTypeId and CatalogBrandId), but I am confused as to what CatalogType and CatalogBrand are used for.

**Comment by ardalis** [comment]
If you mean in BlazorAdmin those properties are just used for display purposes.

**Comment by storms-lab** [comment]
I'm talking about the CatalogItem entity in ApplicationCore.

**Comment by michelcedric** [comment]
This properties are the data representatin.
It exists also to create relation in Infrastructure.Data.Config
 https://github.com/dotnet-architecture/eShopOnWeb/blob/main/src/Infrastructure/Data/Config/CatalogItemConfiguration.cs#L28
With that we have a relationship representation to know how to store relational data.
And it also easier during get to know the brand and type of a CatalogItem

**Comment by michelcedric** [comment]
https://github.com/dotnet-architecture/eShopOnWeb/pull/609/commits/e56864ac5711126f8b47a1780f282e7df009b53e
![image](https://user-images.githubusercontent.com/7223553/139704975-d75a4513-5021-4b1a-87f4-c0ab01ecad45.png)
