### ISSUE TITLE
SignalR with SQLDependancy

### ISSUE THREAD

**Issue by abdalhadi** [dotnet-architecture/eShopOnWeb#452]
Please do you have a version with SignalR with SQLDependancy

**Comment by ardalis** [comment]
Se don't have plans to add that support to this sample currently. You can find the docs for SqlDependency in .NET Core here: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/detecting-changes-with-sqldependency

With that you can make a call to a SignalR hub in your app any time the data changes, which should give you the behavior you're describing.
