### ISSUE TITLE
Changing eShop cookie value to username leads to get and manipulate its basket items

### ISSUE THREAD

**Issue by jurajvt** [dotnet-architecture/eShopOnWeb#453]
User not logged in will obtain new GUID for eShop cookie.
When eShop cookie is changed to someones username, it is possible to get and manipulate its basket items.

1. Run application
2. Add some item to the basket or manually create cookie **eShop**
3. Change **eShop** cookie value to "demouser@microsoft.com"
4. Refresh page
5. Add some items to the basket
6. Delete **eShop** cookie
7. Log in as a "demouser@microsoft.com"
8. You will see basket items which you added as a not logged in user

**Comment by michelcedric** [comment]
It was effectively possible to edit and get basket from other user by manipulate the cookie that represent the username of the basket.
Now it fix by https://github.com/dotnet-architecture/eShopOnWeb/pull/609
