### ISSUE TITLE
SendVerificationEmail view cannot find it

### ISSUE THREAD

**Issue by gastori** [dotnet-architecture/eShopOnWeb#457]
Cannot find the View SendVerificationEmail used managecontroller.cs

**Comment by michelcedric** [comment]
fix bad redirection on click on send verification link
https://github.com/dotnet-architecture/eShopOnWeb/pull/608/commits/6e7a6db63e115d1a6b95d1f4e8a17a4ea26363f4#diff-81ec1b43e620e55e3f1a84e88f645451a858b5452d3d2f064f40fd3bdf0630ebL128
