### ISSUE TITLE
Specification select specific columns from multiple tables

### ISSUE THREAD

**Issue by abdalhadi** [dotnet-architecture/eShopOnWeb#458]
For performance; when we build some queries, we may need to get data from multiple columns, and each column from a different table, so we have to get the required columns to overcome performance issues.
but how may we implement this using specification used in the project?

**Comment by fiseni** [comment]
Hey @abdalhadi,

You can use `Select` functionality through specifications if you want to get only certain columns. Refer to [BlogNamesSpecification](https://github.com/ardalis/Specification/blob/master/ArdalisSpecification/tests/Ardalis.Specification.IntegrationTests/SampleSpecs/BlogNamesSpecification.cs) as an example usage.

But, you won't be able to get columns from different tables in one single query. You can't achieve that even if working directly with DbContext. Show me an example.
