### ISSUE TITLE
Specification with complex logic

### ISSUE THREAD

**Issue by abdalhadi** [dotnet-architecture/eShopOnWeb#459]
Some times we have complex logic, but criteria in the specification is read-only, and the only way to set criteria is by passing the expression to the base class in the constructor, so how can we implement complex expression using existing specification

**Comment by fiseni** [comment]
Hey @abdalhadi,

That's the case in the old version of Ardalis.Specification package. There is a new API in the new version (> 4.0.0).
You don't have to pass it as an argument to the base constructor. Now you can do it more effectively in the constructor body.

Refer to [CustomerOrdersWithItemsSpecification](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Specifications/CustomerOrdersWithItemsSpecification.cs) as an example usage.

**Comment by ardalis** [comment]
Also be aware that specifications are part of the domain model and meant to return entities/aggregate that you're going to work with. If you just need to display some rows from the database, consider using a separate read model and just make custom queries to the database. Don't bother trying to involve your domain model for such things, which are almost always read-only.

**Comment by fiseni** [comment]
This comment of @ardalis is even more valid for the other issue you opened #458.
In that scenario, it seems you just need to read some data (I assume you're creating a report), so no need to go through the domain model at all.

**Comment by abdalhadi** [comment]
@fiseni  @ardalis  many thanks for the replay.
Really I agree with you about having a separate read model, and I already did it in this way, as I build my project with huge data, so I get specific records from different tables for list view (i do not use include).
And for this point, I suggest having a sample for it, with selecting columns from multiple tables. #458

**Comment by ardalis** [comment]
Closing now - feel free to comment if you have more questions.
