### ISSUE TITLE
Versioning with Endpoints

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#467]
How to implement API versioning with Endpoints approach? Normally I used to apply API Versioning using the `[ApiVersion("x.x")]` attribute to the controller.

```c#
[Route("api/authors")]
[ApiController]
[ApiVersion("2.0")]
public class AuthorController : ControllerBase
{
...
```

But with Endpoints approach I'm not able to apply `[ApiVersion("x.x")]` attribute. 

```c#
[HttpGet("api/catalog-brands")]
[ApiVersion("2.0")] // not possible?
[SwaggerOperation(
    Summary = "List Catalog Brands",
    Description = "List Catalog Brands",
    OperationId = "catalog-brands.List",
    Tags = new[] { "CatalogBrandEndpoints" })
]
public override async Task<ActionResult<ListCatalogBrandsResponse>> HandleAsync(CancellationToken cancellationToken)
{
...
```

Any inputs/suggestions on applying versioning with endpoints?

**Comment by ardalis** [comment]
Have you tried applying it to the Endpoint class, just as you would apply it to the Controller class? Endpoint classes inherit from BaseController so I suspect that will work fine.

**Comment by fingers10** [comment]
@ardalis Yeah that works. Thanks for the clarification.
