### ISSUE TITLE
what is CorrelationId and why it is used?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#468]
What is `CorrelationId` and what is it's real use? Do I need to add `CorrelationId` and `CustomSchemaFilters` in my project? Please explain.

**Comment by ardalis** [comment]
The CorrelationId should be passed through the life of the request and used in any logging or diagnostics. It enables after-the-fact troubleshooting to trace behavior from the client's originating request to the server and through to any other microservice calls the server might call, relating them all together. This lets you see everything that happened during the request across all dependencies.
