### ISSUE TITLE
No need of CQRS with Endpoints approach?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#469]
I used to follow `CQRS` approach in my projects with the help of `Mediatr`. `Mediatr` will dispatch the `Command`/`Query` to get the work done. With Endpoint it looks like the `Mediatr` stuff is gone and instead the `Command`/`Query` can be run directly on the endpoint class? can we move all logics inside `Command`/`Query` to the Enpoint class `HandleAsync`?

**Comment by ardalis** [comment]
Generally, yes. There are still benefits to MediatR like pipeline behaviors, though.
