### ISSUE TITLE
Is it possible to add decorator to API Endpoints to enable extra functionalities like logging?

### ISSUE THREAD

**Issue by fingers10** [dotnet-architecture/eShopOnWeb#472]
@ardalis Is it possible to add decorator to Endpoints to enable extra actions in the endpoint execution pipeline? For example, I would like to log my endpoint request data. I don't wanna end up adding logging into each endpoint. Instead a decorator and apply the decorator to the selected endpoints so that it gets executed in the Endpoint Handle Pipeline?

**AuditLogDecorator:**

```c#
public class AuditLoggingDecorator<TRequest, TResponse> : BaseAsyncEndpoint<TRequest, TResponse>
{
    private readonly BaseAsyncEndpoint<TRequest, TResponse> _endpoint;

    public AuditLoggingDecorator(BaseAsyncEndpoint<TRequest, TResponse> endpoint)
    {
        _endpoint = endpoint;
    }

    public override async Task<ActionResult<TResponse>> HandleAsync(TRequest request,
        CancellationToken cancellationToken)
    {
        string requestJson = JsonSerializer.Serialize(request);

        // Use proper logging here
        Console.WriteLine($"Endpoint of type {request.GetType().Name}: {requestJson}");

        return await _endpoint.HandleAsync(request, cancellationToken);
    }
}
```

**AuditLogAttribute:**

```c#
[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
public sealed class AuditLogAttribute : Attribute
{
    public AuditLogAttribute()
    {
    }
}

```

**Endpoint:**

```c#
[AuditLog]
public override async Task<ActionResult<ListCatalogBrandsResponse>> HandleAsync(CancellationToken cancellationToken)
{
...
```

With the above setup, `HandleAsync` inside `AuditLogDecorator` is not getting executed. Am I missing any hooks? Please assist.

**Comment by ardalis** [comment]
Sure, I don't see any problem with that. It looks like it should work.

This is probably a better issue for GitHub.com/ardalis.ApiEndpoints though.

Also if you're trying to create a pipeline, you might be better off using MediatR for that, and have your endpoints work directly with MediatR.
