### ISSUE TITLE
Implement transactions

### ISSUE THREAD

**Issue by aorlenko83** [dotnet-architecture/eShopOnWeb#483]
Could you show some good example of database transaction implementation? For instance, there is _basketService.TransferBasketAsync method, which performs sequential update, and then delete operations. However, in real life it would probably make sense to have these operations be executed in 'all or nothing' approach, so that if Update succeeded and Delete didn't, we don't have inconsistent data.

**Comment by fiseni** [comment]
There are various ways to achieve that. But, considering the existing infrastructure, the simplest way might be to expose `SaveChanges` in your repository.
Update your repository methods as following

```
public async Task<T> AddAsync(T entity, bool saveChanges = true)
{
    dbContext.Set<T>().Add(entity);

    if (saveChanges)
    {
        await SaveChangesAsync();
    }

    return entity;
}
public async Task UpdateAsync(T entity, bool saveChanges = true)
{
    dbContext.Entry(entity).State = EntityState.Modified;

    if (saveChanges)
    {
        await SaveChangesAsync();
    }
}
public async Task DeleteAsync(T entity, bool saveChanges = true)
{
    dbContext.Set<T>().Remove(entity);

    if (saveChanges)
    {
        await SaveChangesAsync();
    }
}
public async Task SaveChangesAsync()
{
    await dbContext.SaveChangesAsync();
}
```

Then, you can just go and use it as shown below

```
await _basketRepository.UpdateAsync(userBasket, saveChanges: false);
await _basketRepository.DeleteAsync(anonymousBasket, saveChanges: false);

await _basketRepository.SaveChangesAsync();
```

**Comment by aorlenko83** [comment]
Thanks. While I'd agree that this is the simplest way for this particular case, my question probably was to show some more scalable and elegant way to do this. For example, this approach is not going to work if we'd need to perform changes in few repositories within single transaction, since it'd be not clear which repo needs to call SaveChangesAsync. 
And of course there are various patterns and ways to do the job. I'm just thinking that it'd be really helpful to the community to have some use case of transaction inside eShopOnWeb, since this is pretty popular 'best practice' repo among c# developers. And at the same time, transactions are very common in real world applications, so I think the transaction implementation example would make the repo even more useful.

**Comment by fiseni** [comment]
Actually, it will work even across repositories. Yes, conceptually will be an issue; from which repository you should call it (from all of them would work).

Creating one dummy UoW, would clear that dilemma, no saves within the repository, commit will always be done through IUnitOfWork.
```
public interface IUnitOfWork
{
    Task SaveChangesAsync();
}

public class UnitOfWork : IUnitOfWork
{
    private readonly DbContext _dbContext;

    public UnitOfWork(DbContext _dbContext)
    {
        this._dbContext = _dbContext;
    }

    public virtual async Task SaveChangesAsync()
    {
        await _dbContext.SaveChangesAsync();
    }
}
```

I might say in the majority of cases, this will cover all your needs, and I personally don't favor additional transaction abstractions on top of DbContext. Anyhow, this is correct only when your app serves atomic requests which are isolated within their boundaries (this sample app in a way does that). If you have use cases where you need several scopes per request, then you might need more complex infrastructure.

There was a short discussion here on the subject https://github.com/dotnet-architecture/eShopOnWeb/issues/473

Generally, I do understand what you're requiring, and hopefully, for the sake of demonstration, some more complex infrastructure will be showcased here.

**Comment by aorlenko83** [comment]
That makes sense, thanks!
