### ISSUE TITLE
docker-compose build does not work

### ISSUE THREAD

**Issue by punkouter2021** [dotnet-architecture/eShopOnWeb#502]
I get alot of these type errors below..

HELP

app/src/PublicApi/PublicApi.csproj : error NU3028: Package 'System.Security.Principal.Windows 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/app/src/PublicApi/PublicApi.csproj : error NU3037: Package 'System.Security.Principal.Windows 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/app/src/PublicApi/PublicApi.csproj : error NU3028: Package 'System.Security.Principal.Windows 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/app/src/PublicApi/PublicApi.csproj : error NU3028: Package 'System.Security.Cryptography.Xml 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/app/src/PublicApi/PublicApi.csproj : error NU3037: Package 'System.Security.Cryptography.Xml 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/app/src/PublicApi/PublicApi.csproj : error NU3028: Package 'System.Security.Cryptography.Xml 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
  Failed to restore /app/src/PublicApi/PublicApi.csproj (in 6.74 sec).
ERROR: Service 'eshoppublicapi' failed to build : The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

**Comment by augustoproiete** [comment]
It's happening everywhere... NuGet broke today. You can see more details and possible workarounds here: https://github.com/NuGet/Home/issues/10491

**Comment by nishanil** [comment]
Yes, we are tracking the status with NuGet team. Alternatively, you can try the workaround mentioned here https://github.com/NuGet/Announcements/issues/49#issuecomment-768766265

**Comment by punkouter2021** [comment]
oh yes., I see.
