### ISSUE TITLE
CatalogItemOrdered  PictureUri 

### ISSUE THREAD

**Issue by yigith** [dotnet-architecture/eShopOnWeb#504]
Hello, 

PictureUri is stored on CatalogItemOrdered so be able to show product image on order summary page. What if the admin updates picture of the catalog item later and the picture file is deleted. When the buyer wants to look at his/her old purchases, s/he won't be able to see the image.

https://github.com/dotnet-architecture/eShopOnWeb/blob/5aa3993c845278cb07cf8f13e5593b288ca9a393/src/ApplicationCore/Entities/OrderAggregate/CatalogItemOrdered.cs

**Comment by ardalis** [comment]
In a production app the images would likely be stored on a CDN and rarely if ever deleted, only new ones added.

**Comment by yigith** [comment]
> d

If the picture is updated by admin after the order has been placed, is it assumed that the CND server will show the image with the same URL? And if the URL changes, should we still keep the old catalog item picture with the previous file name/CDN URL so that past order summaries can be load with all product images when requested?

**Comment by ardalis** [comment]
It depends™

It's definitely worth considering, but it's beyond the scope of this demo application.

Is the new photo a better photo of the same product? Higher quality, etc, but still showing the same item? Then sure, replace it.

Is the new photo of a newer version of the product? Then probably create a new image and use the new image with new orders (and in the catalog). Ideally use a whole new product, too, but even if not it probably makes sense to use the new image for the new version of the product (matching what is actually shipped to people) but you could keep the old image for folks who actually bought the thing shown in that image.

Right?

**Comment by yigith** [comment]
True. It also makes sense to keep the old images for past records. And I understand that this project mainly targets showing an architectural pattern, which I really appreciate. I teach my students clean architecture by applying the architectural pattern to our own project by simplifying some parts.

In our project, we will probably store images in an upload folder and for simplicity, I will consider uploading the new image with the same name.  Thanks for taking time for answering our questions and for all your efforts on these beautiful sample projects.
