### ISSUE TITLE
Referencing ApplicationCore from Infrastructure and Web problem

### ISSUE THREAD

**Issue by jurajvt** [dotnet-architecture/eShopOnWeb#51]
Where is the problem with referencing ApplicationCore project from Infrastructure or Web project?

Cloned this repository, or tried new, scratch solution. When referencing .NET Standard 2.0 class library from .NET Core 2.0 project, problem with compiling or IntelliSense appears (Cannot resolve symbol 'ApplicationCore').

Am I only one with this problem?

Visual Studio CE 2017 v15.3.5

**Comment by jurajvt** [comment]
Problem lies in ReSharper. Updated to new versions and runs fine.

**Comment by ardalis** [comment]
Great, glad you got it sorted out.
