### ISSUE TITLE
Is this ASP.NET core login related security vulnerability?

### ISSUE THREAD

**Issue by ravimpatel** [dotnet-architecture/eShopOnWeb#519]
**Test:**
1. Login to eShopOnWeb. (test user name we used : neel)
2. Record any authorized web request using Fiddler or web developer tools etc. We recorded /basket request of eShopOnWeb sample website which shows personalized shopping cart of the logged in user.
Logout.
3. Close browser.
4. Open website in guest mode. (do not login). You may choose a different browser altogether.
5. Replay step 2. (This uses exact same headers containing cookies, token etc.)

**Observation:**
This successfully returns shopping cart items of the user neel.

**Is this a login related vulnerability? I think it is!! Shouldn't the token expire (session destroy) with logout?**

**Comment by LeiYangGH** [comment]
how can you record and replay, if the server is not accessible to you and is using https?

**Comment by michelcedric** [comment]
The project use a token store in a cookie for the authentication.
![image](https://user-images.githubusercontent.com/7223553/139671985-66eeda20-26be-4d9c-b820-e3b01ecafc01.png)

On logout the identity remain valid until the cookie expiration.
To avoid waiting the cookie expiration, I propose to store In in memroy cache a list of revoked cookie value. 
The inconvenient if the sever restart you lost the in memory cache, you can use a redis cache or other persistency cache mecanism to not lost this one.
The element in the cache will expire after 1 hour, same time of the cookie duration. In this way the cookie value could not used up to the end of cookie expiration time and after automaticly destroy in cache.
https://github.com/dotnet-architecture/eShopOnWeb/pull/605

**Comment by michelcedric** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-5.0#react-to-back-end-changes
The user remains signed into the app as long as the authentication cookie is valid.
To implement an override for the ValidatePrincipal event, write a method with the following signature in a class that derives from CookieAuthenticationEvents:

**Comment by michelcedric** [comment]
Point of attention : replace IMemoryCache by disctribud cache if you are in multi-host scenario
https://github.com/dotnet-architecture/eShopOnWeb/pull/605/commits/b42dc20bb627444a1c2836773110b4fd81943495
