### ISSUE TITLE
Bad architectural advices.

### ISSUE THREAD

**Issue by Tickles** [dotnet-architecture/eShopOnWeb#524]
Hi!

I've found several bad architectural solutions with this eshop. 
1. It is not loose coupled
2. There is going to be reference issues
3. The configurations for dependency injection is all in web project. Hard coupled, referencal issues etc.
4. One of the configurations got a faulty reference. 

I would strongly advice to update it further to fit SOLID and Clean Architecture for real. I know this might only be an example but there are people out there taking this as how it should look like.

Keep up the good work.

**Comment by ardalis** [comment]
Hi @Tickles just saw your docs issue and responded there - glad to see this is in fact the reference you were making.

Can you elaborate, perhaps in separate issues?

1. How is it not loosely coupled? What specific instance of coupling are you hoping to change?
2. What "reference issues" are you referring to? Do they exist now, or are you predicting they would occur if this sample were extended?
3. By default, ASP.NET Core configures dependent services in Startup.ConfigureServices. This example mostly follows that approach, it's true.
4. "One of the configurations" can you be specific? If there is an issue, we can fix it or you're welcome to create a specific issue and perhaps a pull request that addresses it.

Thanks for your feedback and assistance!

**Comment by fiseni** [comment]
The Web project is the root composition, that's why DI configurations are there. You can surely create `IServiceCollection` extensions for each project separately and place project-specific configs there. But, in that case, you'll have to reference the `Microsoft.Extensions.DependencyInjection` namespace from those projects. That's the tradeoff. Do you want your core/domain projects to reference infrastructure-related packages? What do you value more?

That approach fits really well in feature-based modules (vertical layering). Each module exposes the DI configurations separately. But, in our case here, we have a more horizontal layering, and you won't have any benefit of splitting up the configs.

**Comment by Tickles** [comment]
well, as i see it each project should hold its own DI.cs = loose coupled. In web you should add the different  .AddCOnfigureServices. in startup. This way you would only need to keep track of references in each project. Sure you wont be able to keep it 100% clean but for instans you would be able to just remove .AddConfigureService from let's say Application since Domain should be kept outside and go through the Application layer. This would also mean there is only one way referencing. As an example following the architecture with configuration folder in web would mean i have to keep referencing appsettings class(just as an example) instead of just doing it the SOLID way and ref it once in right layer by DI and in the web just get what i need from the configuration. Hope ill make sense, but if you want to know what i mean you could take a look at Jason Taylors version of Clean Architecture.

**Comment by fiseni** [comment]
Honestly, this has nothing to do with SOLID. Jason Taylor's version is a great one, but it's applicable for larger projects, where you need enterprise-wide logic, and then create app layer for each application respectively. We had some discussions on this subject, refer [here](https://github.com/dotnet-architecture/eShopOnWeb/issues/165#issuecomment-440737177).

As for the DI configurations, there is a tradeoff. For instance, do you want your enterprise-wide project to reference the DI NuGet package? None of these approaches is bad per se. Choose whichever fits you better. 

But, this has nothing to do with modularity. When we talk of loose coupling, we mean something is easily replaceable. All DI configs are located in one place, so you can easily switch any implementation. That's the point. But, in either case, you will need to recompile the solution. It's the same amount of work.

If you want to be able to inject the configs in runtime, then here is an example Nuget [package](https://github.com/fiseni/PozitronDev.DIConfiguration). But, use this option sparingly. Use it only if it's really beneficial in a given case.

**Comment by Tickles** [comment]
the architectural design and how its implemented has everything to do with SOLID. But since you are not willing to improve the solution i wont make you. 

Yes Jason Taylors solution for CA is for larger applications but you can still use the main idea for smaller ones. You do not need to be stuck on how it is implemented but just simply use the good parts.

I'll leave it at that.

**Comment by fiseni** [comment]
I'm not a maintainer here, but I do believe the maintainers would accept any constructive suggestion and any help is welcome.

So, as already suggested, you can open separate issues for each topic separately. The initial description is a bit vague, so you can try to elaborate your concerns in more detail, provide suggestions and examples, prepare a PR perhaps. I believe that approach will generate more constructive discussions.
