### ISSUE TITLE
[question]What is the supposed way to implement pagination and sorting in this repository and specification design?

### ISSUE THREAD

**Issue by wyshmily** [dotnet-architecture/eShopOnWeb#53]
I am a bit confused. 
Should I use it like this: List(spec).OrderBy().Skip().take()，and in this case the list(spec) fuction in fact return s IQueryable, is it?

Or should I extend the IRespository and IAsyncRespository with interfaces like ListPage(ISpecification specification, int page, int mumber)，and ListPageAsync(ISpecification, int page, int number)

**Comment by ardalis** [comment]
Currently the app does this here, for the catalog paging:
https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Services/CatalogService.cs#L36

This implementation loads the full list into memory, then pages it. This is fine for the current site for two reasons:
1) There are very few total items.
2) The call to GetCatalogItems is cached by CachedCatalogService, so the full collection of catalog items is only fetched from the database infrequently, and then is kept in the cache for all future requests until it times out.

If you have a situation in which you require paging and your data source is large enough that you don't want to cache all of it (say, 1000 items or more), then you probably would want to perform the paging within the repository, most likely with an overload as you suggested in your question (ListPage).

**Comment by wyshmily** [comment]
@ardalis Thanks a lot !

**Comment by wyshmily** [comment]
@ardalis 
What about sorting? Pagination is always depending on sorting.
Is there a way to put EF operations  OrderBy().ThenBy() into our ISpecification ?

**Comment by ardalis** [comment]
This looks like it would do what you want: https://stackoverflow.com/a/25244226/13729. You're welcome to add a PR with the functionality if you get it working. (sorry for the late response).
