### ISSUE TITLE
Is OrderId missing on OrderItem?

### ISSUE THREAD

**Issue by yigith** [dotnet-architecture/eShopOnWeb#530]
https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Entities/OrderAggregate/OrderItem.cs

I understand that EF figures out and creates the OrderId field and foreign key on the database but shouldn't still there be a property 'OrderId' as BasketItem has BasketId property.

**Comment by ardalis** [comment]
If you needed it somewhere, you could add it and it would not hurt anything. The app works without it currently, so currently it's not needed so it's not defined explicitly (it's still there as a shadow property and in the database like you mention).
