### ISSUE TITLE
Question for form submit

### ISSUE THREAD

**Issue by JeffXieXiwei** [dotnet-architecture/eShopOnWeb#54]
In Views/Catalog/Index.cshtml, there is no submit in following form. How does it work?

        <form asp-action="Index" asp-controller="Catalog" method="post">
            <label class="esh-catalog-label" data-title="brand">
                <select asp-for="@Model.BrandFilterApplied" asp-items="@Model.Brands" class="esh-catalog-filter"></select>
            </label>
            <label class="esh-catalog-label" data-title="type">
                <select asp-for="@Model.TypesFilterApplied" asp-items="@Model.Types" class="esh-catalog-filter"></select>
            </label>
            <input class="esh-catalog-send" type="image" src="images/arrow-right.svg" />

        </form>

**Comment by ardalis** [comment]
The `<input type="image">` button is the submit button, in this case. There's some additional CSS that helps the experience (color change and pointer change on hover, for instance).

See: https://stackoverflow.com/questions/7935456/input-type-image-submit-form-value
