### ISSUE TITLE
The link, "Working with data using EF Core" should be repaired

### ISSUE THREAD

**Issue by jjjohn538** [dotnet-architecture/eShopOnWeb#635]
That link currently points to the same content as the "Creating an ASP.NET Core Web App". It should point to the content at:
https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps

Jesse Johnson

**Comment by FarhadFazly** [comment]
unsbsruco

**Comment by ardalis** [comment]
@jjjohn538 I don't know where this link is that needs to be fixed. Closing for now but reopen with more info if you can.

**Comment by jjjohn538** [comment]
Very well. I have not been able to reproduce the behavior I previously reported.
