### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by ArsenioInojosa** [dotnet-architecture/eShopOnWeb#650]
Hi all,

Please update the instructions to be consistent with ASP.NET Core 6.

Does the example of using SQL in memory no longer exist?

**Configuring the sample to use SQL Server
Update Startup.cs's ConfigureDevelopmentServices method as follows:**

```
public void ConfigureDevelopmentServices(IServiceCollection services)
{
    // use in-memory database
    //ConfigureTestingServices(services);

    // use real database
    ConfigureProductionServices(services);

}
```

Greetings!

**Comment by michelcedric** [comment]
https://github.com/dotnet-architecture/eShopOnWeb/issues/664

The section : Configuring the sample to use SQL Server is updated

**Comment by ardalis** [comment]
Thanks @michelcedric !
