### ISSUE TITLE
ShipToAddress Mapping Ignores Required

### ISSUE THREAD

**Issue by yigith** [dotnet-architecture/eShopOnWeb#656]
Although the fields ZipCode, Street, Country and City are configured as required, the related migration shows that they are not.

https://github.com/dotnet-architecture/eShopOnWeb/blob/main/src/Infrastructure/Data/Config/OrderConfiguration.cs

https://github.com/dotnet-architecture/eShopOnWeb/blob/main/src/Infrastructure/Data/Migrations/20201202111507_InitialModel.cs

```
...
            a.Property(a => a.ZipCode)
                .HasMaxLength(18)
                .IsRequired();
...
```

```
...
            ShipToAddress_ZipCode = table.Column<string>(type: "nvarchar(18)", maxLength: 18, nullable: true)
...
```

**Comment by erjain** [comment]
I am closing this issue as of now. Please feel free to reopen it, if needed.
