### ISSUE TITLE
Update ReadME

### ISSUE THREAD

**Issue by jaymikd** [dotnet-architecture/eShopOnWeb#664]
Post Net 6 upgrade, startup.cs file has been removed, however the Read me still provides the details with respect to Startup.cs file to execute the application locally. 

May we have the same udpated.

**Comment by michelcedric** [comment]
Thanks for your remarks, I updated my last pull request to adapt the readme.
https://github.com/dotnet-architecture/eShopOnWeb/pull/662/commits/91e153f3169eff8940c21c8ca8d9b16414d88c1e 
Now waiting validation by @ardalis 
Have a good day ;)
