### ISSUE TITLE
Can't create SQL Server databases

### ISSUE THREAD

**Issue by DannyAllegrezza** [dotnet-architecture/eShopOnWeb#67]
Hi team,

First off, thank you for creating this sample project! I've successfully run the project using the in memory db with no issues. I followed the instructions on the README and attempted to run the migrations to create the initial Catalog and Identity databases.

I've got .NET Core 2 SDK installed on my Windows 10 machine. I have SQL Server 2014 installed as well.

1. Modified Program.cs as mentioned in the README file
2. Verified appsettings.json connection strings. I've modified these a few times, but nothing seems to work:

```
// these are the default connection strings included with the project
  "ConnectionStrings": {
    "CatalogConnection": "Server=(localdb)\\ProjectsV13;Integrated Security=true;Initial Catalog=Microsoft.eShopOnWeb.CatalogDb;",
    "IdentityConnection": "Server=(localdb)\\ProjectsV13;Integrated Security=true;Initial Catalog=Microsoft.eShopOnWeb.Identity;"
  },
```

3. Navigate to the Web folder: `C:\Users\Danny\Documents\GitHub\eShopOnWeb\src\Web`
4. Run `dotnet restore` - works fine

```
dotnet ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
dotnet ef database update -c appidentitydbcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
```

Neither of these work. 

Here is the large log shared via a Gist:
https://gist.github.com/DannyAllegrezza/7848a91c241ade453d4cb45598665252

I'm not sure where this problem stems from. It seems as though the database is never being created, which leads to the 

```
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "Microsoft.eShopOnWeb.Identity" requested by the login. The login failed.
Login failed for user 'DESKTOP-HICGBT3\Danny'.
```
errors.

I've created plenty of LocalDB databases with no issues. 

Here is the final error:

```
Error Number:4060,State:1,Class:11
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: One or more errors occurred. (Cannot open database "Microsoft.eShopOnWeb.Identity" requested by the login. The login failed.

Login failed for user 'DESKTOP-HICGBT3\Danny'.)

Unable to create an object of type 'CatalogContext'. Add an implementation of 'IDesignTimeDbContextFactory<CatalogContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```

Any thoughts on this?

**Comment by ardalis** [comment]
It looks like it can't connect to the named db server at all. Make sure you have the appropriately named instance of LocalDB on your machine. In my case, I have several:

![image](https://user-images.githubusercontent.com/782127/31957113-a412d638-b8bb-11e7-84b2-bafe215ec514.png)

You should be able to pick anything, as long as you have it installed. Can you confirm you have one called (localdb)/ProjectsV13 ?

**Comment by yarrgh** [comment]
You mention that you have SQL Server 2014 installed, but, do you have SQL Server Express installed as well? I believe localdb uses SQL Server Express, usually installed with Visual Studio. You can point the connection strings to your existing SQL Server but you'd have to create the databases on the server first.

**Comment by DannyAllegrezza** [comment]
@ardalis @yarrgh thanks for the quick response!

![explorer](https://user-images.githubusercontent.com/7738918/31959910-0f9a14fe-b8c4-11e7-80af-c24eb654838a.JPG)

I have SQL Server Express 2016 installed as well as SSMS 2014. I have been using localdb for my other projects. I've tried modifying my connection strings multiple times, testing out different servers and databases, including `(localdb)\ProjectsV13` and `(localdb)\MSSQLLocalDB` with no luck.

Just tried the following connection strings:

```
  "ConnectionStrings": {
    "CatalogConnection": "Data Source=DESKTOP-HICGBT3\\\\SQLEXPRESS01;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;Initial Catalog=Microsoft.eShopOnWeb.CatalogDb;User=DESKTOP-HICGBT3\\Danny",
    "IdentityConnection": "Data Source=DESKTOP-HICGBT3\\\\SQLEXPRESS01;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False;Initial Catalog=Microsoft.eShopOnWeb.Identity;User=DESKTOP-HICGBT3\\Danny"
  }
```

which generated these new errors: https://gist.github.com/DannyAllegrezza/89232ac7aa17969cb0342343b131b439

**Comment by DannyAllegrezza** [comment]
Closing this issue.

So I'm not really sure which fixed the problem, but I took these steps:

* Delete the existing migrations, see if I could recreate them.
At first, this did *not* work. I received the following error:
```
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: One or more errors occurred. (Instance failure.)
Unable to create an object of type 'AppIdentityDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<AppIdentityDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```

Googling the error led me to this [StackOverflow ](https://stackoverflow.com/questions/45782446/unable-to-create-migrations-after-upgrading-to-asp-net-core-2-0#comment78530397_45782446)post which mentions how the seed data could cause an issue. 

* I commented out the lines below `//Seed Data` in `ConfigureProduction()` and `ConfigureDevelopment()` which looked like:
```
            //Seed Data
            CatalogContextSeed.SeedAsync(app, catalogContext, loggerFactory)
            .Wait();

            var defaultUser = new ApplicationUser { UserName = "demouser@microsoft.com", Email = "demouser@microsoft.com" };
            userManager.CreateAsync(defaultUser, "Pass@word1").Wait();
```
**Aside**: Where do these methods get called from? I tried to view the call hierarchy and did not see where they are called from...?

* After commenting out the seed data, I was able to run the create migration commands successfully.. finally!

```
λ dotnet ef migrations add InitialIdentityModel --context appidentitydbcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj -o Identity/Migrations
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Danny\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'AppIdentityDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Done. To undo this action, use 'ef migrations remove'

λ dotnet ef migrations add InitialModel --context catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj -o Data/Migrations
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Danny\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[100403]
      Entity Framework Core 2.0.0-rtm-26452 initialized 'CatalogContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Done. To undo this action, use 'ef migrations remove'
```

Then I was able to run the `dotnet ef database update` commands which successfully created the databases. After this, I uncommented the seed functionality and started up the application, which is now working for me.

![working](https://user-images.githubusercontent.com/7738918/31965983-21605a82-b8d7-11e7-8200-1ddeed56158f.JPG)

**Comment by ardalis** [comment]
Are you running on the latest version of the master branch? The seed data thing is a known EF Core 2.0 breaking change that was fixed in the latest version of the sample. The seed data is now done in Program.cs:

https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Program.cs#L18-L36

If you were still seeing it in Startup.cs I think you were on an older version.

**Comment by DannyAllegrezza** [comment]
Oh man, I was behind by like 17 commits. Glad to know about the seed data thing. I appreciate all of the help @ardalis 👍 

btw: I've really enjoyed all of your PluralSight courses. Great stuff!
