### ISSUE TITLE
OnPostUpdateTo50Successfully test fails on non-standard cultures

### ISSUE THREAD

**Issue by AbdelHajou** [dotnet-architecture/eShopOnWeb#698]
https://github.com/dotnet-architecture/eShopOnWeb/blob/a87f571ff26a797e60c1dfab4220ab24d7dff882/tests/FunctionalTests/Web/Pages/Basket/IndexTest.cs#L57

This assertion fails when the tests are run on a system with some locales different from the standard en-US locale. On my PC, with the default culture set to nl-NL, the test fails because the output value is 97450,00 instead of the expected 974.50.

Setting the culture to en-US explicitly solves this issue and makes the test pass, but this should probably be fixed on a more global level.
```csharp
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-US");
```

**Comment by martinandersen3d** [comment]
Thanks - I just had the same, using a danish (da\_DK) keyboard.

I have currently inserted it into the test here.. but what is a more correct place to put it?

Thanks 🙏😀

![](https://user-images.githubusercontent.com/19984581/162289928-7fd18301-38fd-40ad-b274-8270304fdbaf.png)

**Comment by michelcedric** [comment]
There are 2 issues.
The price was sent by the client easily to fraud (the client can determine itself the pricing)
In the unit test the price was an hardcoded string but for now the price format is made by the server.
https://github.com/dotnet-architecture/eShopOnWeb/blob/main/src/Web/Pages/Basket/Index.cshtml#L57
It's more logical to put a decimal in unit test and use the same format
`.ToString("N2")`
