### ISSUE TITLE
Images for Wiki

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnWeb#70]

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/32811156-1e40a2bc-c953-11e7-9fde-c60f7bce398d.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/32811359-0c8b9ab2-c954-11e7-8bce-71b36af4b4fe.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/32811823-9245f772-c956-11e7-9b87-bbeaa4154bb9.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/32811855-baf12976-c956-11e7-98a3-568e4dd14a6d.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/55909061-0996f700-5ba9-11e9-8924-4b02b61fe9d2.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/55909174-5549a080-5ba9-11e9-8364-5ac9b5d4c78e.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/55909229-76aa8c80-5ba9-11e9-8dab-5c48580f69ad.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/74948402-48512c80-53ca-11ea-948a-58d037440888.png)
