### ISSUE TITLE
Getting compile error with ardalis spec pattern

### ISSUE THREAD

**Issue by amadarohan** [dotnet-architecture/eShopOnWeb#701]
hi, hopping you all are having a good time.

I'm using the ardalis package and based on tutorial on website and this repo I have implemented. But when I trying to compile the the project I get the following Error:

The call is ambiguous between the following methods or properties: 'IReadRepositoryBase<T>.GetBySpecAsync<Spec>(Spec, CancellationToken)' and 'IReadRepositoryBase<T>.GetBySpecAsync<Spec>(Spec, CancellationToken)'
1>Done building project "Test.Test.Application.csproj" -- FAILED. 

apparently the "GetBySpecAsync" has been registered more than one time and for this matter the mentioned error in compile times get generated. 

I will be thanks full if any solution will be given. if it's needed more to post the codes I have been using for more clearance please say so.

**Comment by michelcedric** [comment]
Hi
The implementation in the EshopOnWeb seems working well.
Could you share you code to have a look on it?

**Comment by amadarohan** [comment]
the problem was for our .net version. everything's ok now. ^_^
