### ISSUE TITLE
Question about loading related data in repository

### ISSUE THREAD

**Issue by Anton987** [dotnet-architecture/eShopOnWeb#73]
Hello,

How can i use multiple include statements inside a repository? 
Why isn't my code below working?
`
var result = _dbContext.Object
.Include(ans => ans.ObjectOther)
.Include(ans => ans.ObjectOther.Select(o => o.ObjectOtherDetail))
.SingleOrDefault(a => a.Id == id); 
`
Regards

**Comment by ardalis** [comment]
You can use multiple includes, but I don't think you can put a .Select inside of it. This GitHub sample isn't for general Q&A, though. You're probably better off posting a question like this to StackOverflow.
