### ISSUE TITLE
Where are the specific EfRepository<T> types injected in the PublicApi project?

### ISSUE THREAD

**Issue by claudeHasler** [dotnet-architecture/eShopOnWeb#749]
In the Program.cs i see:

```
builder.Services.AddScoped(typeof(IRepository<>), typeof(EfRepository<>));
```

which is injected into EndPoints and stored:

```
private IRepository<CatalogItem> _itemRepository;
```

But I don't understand how these specific implementations of the interface are resolved.

**Comment by ardalis** [comment]
It's using generics. So the first line you show effectively says any IRepository of *something* that is requested should be satisfied using an instance of EfRepository of *something*. So, when an endpoint requests an `IRepository<CatalogItem>` the DI container responds by providing an instance of `EfRepository<CatalogItem>`.
