### ISSUE TITLE
docker-compose build command is failing

### ISSUE THREAD

**Issue by kedarbindu** [dotnet-architecture/eShopOnWeb#756]
I am trying to clone and build (using docker-compose build) this repository on an Ubuntu 20.04 VM. However, this fails while trying to restore some dependencies using libman. This is the error I get: libman.json: error LIB002: The jquery@3.3.1 library could not be resolved by the cdnjs provider [/app/src/Web/Web.csproj]

here is a slightly longer log console log:
 `Step 7/11 : RUN dotnet publish -c Release -o out 
 ---> Running in ca18bec26643
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /app/src/Web/Web.csproj (in 3.62 sec).
  4 of 5 projects are up-to-date for restore.
  
  Restore operation started
libman.json : error LIB002: The "jquery@3.3.1" library could not be resolved by the "cdnjs" provider [/app/src/Web/Web.csproj]
libman.json : error LIB002: The "twitter-bootstrap@3.3.7" library could not be resolved by the "cdnjs" provider [/app/src/Web/Web.csproj]
libman.json : error LIB002: The "jquery-validation-unobtrusive@3.2.10" library could not be resolved by the "cdnjs" provider [/app/src/Web/Web.csproj]
libman.json : error LIB002: The "jquery-validate@1.17.0" library could not be resolved by the "cdnjs" provider [/app/src/Web/Web.csproj]
libman.json : error LIB002: The "toastr.js@2.1.4" library could not be resolved by the "cdnjs" provider [/app/src/Web/Web.csproj]
libman.json : error LIB002: The "aspnet-signalr@1.0.3" library could not be resolved by the "cdnjs" provider [/app/src/Web/Web.csproj]
  
  One or more libraries failed to restore
  
The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
ERROR: Service 'eshopwebmvc' failed to build : Build failed
`

Searching for this error lead me to this issue https://github.com/aspnet/LibraryManager/issues/685#issue-1276654885

I have tried the solution mentioned in this post (from the same issue): https://github.com/aspnet/LibraryManager/issues/685#issuecomment-1162457924 but it did not resolve it for me.

Can you please help?

**Comment by pheu** [comment]
@kedarbindu I had the same issue. I got it resolved on its own upon building once again.

**Comment by looking4ward** [comment]
Still same issue here with both eShopOnConatiners and eShopOnWeb
"libman.json : error LIB002: The "jquery-validation-unobtrusive@3.2.10" library could not be resolved by the "cdnjs" pro
vider [D:\Shop on Microservices example\eShopOnWeb\src\Web\Web.csproj]"

I did update the dotnet CLI too.
dotnet tool install --global Microsoft.Web.LibraryManager.Cli --version 2.1.175

**Comment by michelcedric** [comment]
It seems Cdnjs updated the API.
The LibraryManager pacakage was adapted and of course we need to update to support it.
https://github.com/aspnet/LibraryManager/commit/ed732a882c619a61b28601d27ba9b00692a3f8cd
