### ISSUE TITLE
BaseSpecification Code Improvement

### ISSUE THREAD

**Issue by aownshah** [dotnet-architecture/eShopOnWeb#76]
The public constructor makes no sense in an abstract class BaseSpecification.

public abstract class BaseSpecification<T> : ISpecification<T>
{
    public BaseSpecification(Expression<Func<T, bool>> criteria)
......
}

As the BaseSpecification can only be initiated by derived types. Please change the constructor to protected as following:

protected BaseSpecification(Expression<Func<T, bool>> criteria)

**Comment by ardalis** [comment]
Thanks!
