### ISSUE TITLE
Unable to load solution in Visual Studio for Mac

### ISSUE THREAD

**Issue by mrlife** [dotnet-architecture/eShopOnWeb#764]
Opening the solution results in this error:

![Screen Shot 2022-07-28 at 2 37 38 PM](https://user-images.githubusercontent.com/213164/181613144-77d3a1e6-3edb-4327-b9e6-648f515ebf81.png)

As another data point, the [eShopOnDapr](https://github.com/dotnet-architecture/eShopOnDapr) solution does open.

Visual Studio for Mac 17.3 Preview build 2083

**Comment by michelcedric** [comment]
HI
All workings fine on my site.
Do you intall .Net 6?
<img width="1437" alt="Screenshot 2022-07-29 at 19 51 21" src="https://user-images.githubusercontent.com/7223553/181816802-a9478ea3-de14-44c9-8391-dc15c3c0d255.png">

**Comment by mrlife** [comment]
@michelcedric Thank you, it does appear to work for me now after trying it again today. I will chalk it up to an anomaly within Visual Studio for Mac.
