### ISSUE TITLE
BasketWithItemsSpecification Code Improvement

### ISSUE THREAD

**Issue by aownshah** [dotnet-architecture/eShopOnWeb#78]
In BasketWithItemsSpecification constructor the code is calling AddInclude which is a virtual method. 
This could lead to a possible problem that if you make a virtual method call in a constructor, and it is not the most derived type in its inheritance hierarchy, that it will be called on a class whose constructor has not been run, and therefore may not be in a suitable state to have that method called.

public BasketWithItemsSpecification(int basketId)
            :base(b => b.Id == basketId)
        {
            AddInclude(b => b.Items);
        }

I would suggest making the BasketWithItemsSpecification as a "sealed" class.

**Comment by ardalis** [comment]
Thanks!
