### ISSUE TITLE
BlazorAdmin can't  open page 

### ISSUE THREAD

**Issue by SebastianGoo** [dotnet-architecture/eShopOnWeb#780]
![Screenshot 2022-09-07 172430](https://user-images.githubusercontent.com/26989739/188842969-d3e897a9-4fd2-49d7-bc49-2055da32e3c5.png)

i do nothing

**Comment by ks1990cn** [comment]
Probably due to no Index.razor and unable to find entry point for page.

**Comment by onurcanyilmaz** [comment]
I've faced this problem. 

Firstly, you should start Web project. Then you should log in with admin account. Finally, when you want to access blazor admin panel, redirect with /admin.

You should see the blazor admin panel

**Comment by SebastianGoo** [comment]
> I've faced this problem.

Thank you. I see what you mean

**Comment by michelcedric** [comment]
I added in the readme how to access the admin page.

 You can configure Visual Studio to start multiple projects, or just go to the PublicApi folder in a terminal window and run dotnet run from there. After that from the Web folder you should run dotnet run --launch-profile Web. Now you should be able to browse to https://localhost:5001/. The admin part in Blazor is accessible to https://localhost:5001/admin
