### ISSUE TITLE
Dependency AspNetCore.Http in Infra or other project?

### ISSUE THREAD

**Issue by marcrib** [dotnet-architecture/eShopOnWeb#81]
I have a situation where I need to have ICurrentUser on both projects

1 - ApplicationCore for any specific rule with user or tenant 
2 - Infra - For global filter in dbContext or repository

The implementation of ICurrentUser have a dependency the Microsoft.AspNetCore.Http

For example:

```
  public class CurrentUser: ICurrentUser
    {
        private readonly IHttpContextAccessor _accessor; //HERE

        public UserSession (IHttpContextAccessor accessor)
        {
            _accessor = accessor;
        }
        public string Name => _accessor.HttpContext.User.Identity.Name;
        public int? TenantId => int.Parse (_accessor.HttpContext.User.Claims.FirstOrDefault (x => x.Type == "TenantId"). ToString ());
        public bool IsAuthenticated => _accessor.HttpContext.User.Identity.IsAuthenticated;
    }
```

I have as dependency Microsoft.AspNetCore.Http, and need to be used in ApplicationCore and Infra (Data / DbContext)

Would it be correct to leave this implementation and dependency on Infra? Or maybe in another layer (eShopOnWeb.Shared for example)? Where would be the best approach?

Suggestions?

**Comment by yarrgh** [comment]
Place the `CurrentUser` in the Web project and `ICurrentUser` in the Core project. Use dependency injection to inject the `ICurrentUser` into the other projects that need it.

**Comment by marcrib** [comment]
Hi @yarrgh, thanks

Other solution is separate the infra projects into other layers

For example:

eShopOnWeb.Infra.Data (DbContext / Repository / Dapper / Others)
eShopOnWeb.Infra.Identity (Asp.Net Identity provider)
eShopOnWeb.Infra.Email (SendGrid)
eShopOnWeb.Infra.Redis (cache)

Would that be bad for clean architecture?

@ardalis Suggestions?

**Comment by CESARDELATORRE** [comment]
It is ok to have multiple infrastructure projects as long as only the Interfaces/Contracts are the ones defined in the Core project.
Then use dependency injection from the application layers (Web project or any other application layer)

**Comment by ardalis** [comment]
I aggree with @CESARDELATORRE and @yarrgh . You can split out infrastructure concerns into different projects *if you find value in that*. I usually don't, but it's certainly an option, and the proposed examples of how you might do so make sense. The most important thing, as Cesar notes, is to make sure your interfaces are in Core, your Infrastructure depends on these interfaces, and that Core has no external dependencies (which it shouldn't if you followed the other steps).

**Comment by marcrib** [comment]
Thanks all
