### ISSUE TITLE
How to work and redirect BlazorAdmin project in Web project

### ISSUE THREAD

**Issue by onurcanyilmaz** [dotnet-architecture/eShopOnWeb#816]
This is a question.

I just want to learn how to work and redirect BlazorAdmin project in Web project.
Could you explain to me that.

Thanks.

**Comment by eyedropsP** [comment]
Hi, I found how to use BlazorAdmin.
BlazorAdmin project is referenced from Web project. Therefore, after launching the Web project, you can check the BlazorAdmin page by accessing a specific URL.
I will write how to do it below.
1. Run Web project
2. Login by admin user (email and password are displayed at the bottom of the login screen)
3. Access ```localhost:5001/admin```.
4. You can access the admin page for the BlazorAdmin project.

**Comment by ardalis** [comment]
I'll try to record another video on eShopOnWeb after it's updated to dotnet 7 and I'll make sure to demonstrate Blazor in there as well.
