### ISSUE TITLE
Fix Multiple DbContext Registration (#703)

### ISSUE THREAD

**Issue by vishnuhorizon** [dotnet-architecture/eShopOnWeb#864]
Hi, i noticed that in the WebTestFixture used for FunctionalTests the DbContexts were registered without removing the existing ones in Program.cs which leads to duplication - With Commit ID - **4304545f19bc404562e16a693e20bbcbdb878d43**

**Comment by skunal012** [comment]
Hi, is this issue resolved?

**Comment by SrushtiPasari94** [comment]
@skunal012 Dbcontext has been removed in line "services.Remove(descriptor)" then new context is registered.
