### ISSUE TITLE
Cannot run update-database

### ISSUE THREAD

**Issue by punkouter** [dotnet-architecture/eShopOnWeb#87]
PM> dotnet ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
C:\Program Files\dotnet\sdk\2.1.104\Microsoft.Common.targets(127,3): error MSB4024: The imported project file "C:\Users\MHerb\Downloads\eShopOnWeb\src\Infrastructure\obj\Infrastructure.csproj.EntityFrameworkCore.targets" could not be loaded. Unexpected end tag. Line 25, position 4. [C:\Users\MHerb\Downloads\eShopOnWeb\src\Infrastructure\Infrastructure.csproj]
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
PM>

**Comment by ricardo-b-dtakers** [comment]
Did you run "dotnet restore" command before?
What's the path you're tryting to run "dotnet ef..." commands? Is it Web folder?

**Comment by punkouter** [comment]
I didn't point it to web. works now
