### ISSUE TITLE
Not able to run WebRazorPages on Linux server

### ISSUE THREAD

**Issue by rajnikaushal** [dotnet-architecture/eShopOnWeb#88]
Hi,
First i have added docker support to both applications - Web and WebRazorPages and it's working fine at my local and i am able to run both applications.
Then i am trying to deploy this application on Linux server. Web is deploying fine but for WebRazorPages it's giving me following error:
'Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409'
Please suggest how can i resolve this error.

I have one more query, Docker inbuilt added container ip for both applications, then how can we access these application outside.
Do we need to redirect these ip's ?
Please also guide on these points.

Thanks!
Rajni

**Comment by ratanparai** [comment]
You should learn about docker first. There is a good 6 part [Getting Started](https://docs.docker.com/get-started/) tutorial in docker.

**Comment by ardalis** [comment]
Are you still having problems? Can you share your Dockerfile(s)?

**Comment by ardalis** [comment]
Closing - let me know if this is still an issue and please provide more info.
