### ISSUE TITLE
Architect Modern Web Applications edition 7th not available as PDF

### ISSUE THREAD

**Issue by kohanyirobert** [dotnet-architecture/eShopOnWeb#905]
[The link leading to the PDF version of the related book](https://aka.ms/webappebook) leads 7th edition/revision of the book, while [the webpage](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/) is up-to-date.

Not sure if this is the best place to raise this. `dotnet/docs` seemed pretty convoluted. A PDF guy trying a shot here.

**Comment by punkouter23** [comment]
Ive read that.. I wish it was more specific to the code of eShopOnWeb

**Comment by jamesmontemagno** [comment]
I think they are in sync now from what I can see.
