### ISSUE TITLE
LoginWithRecoveryCode.cshtml missing namespace reference

### ISSUE THREAD

**Issue by jimlamb** [dotnet-architecture/eShopOnWeb#92]
I had to add 
    @using Microsoft.eShopWeb.RazorPages.Pages.Account.Manage

to LoginWithRecoveryCode.cshtml to fix some unresolved references while running dotnet publish.

**Comment by ardalis** [comment]
I'm unable to reproduce this issue. I can build locally, navigate to that page locally, and publish to a local folder without issue. Can you provide more information?
