### ISSUE TITLE
The functional tests do not work with RazorPages

### ISSUE THREAD

**Issue by rosspace** [dotnet-architecture/eShopOnWeb#96]
I tried implementing the functional tests for my own project but I am using RazorPages and I get the following error:

The type or namespace name 'RazorPages' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)

The RazorPages project runs from Visual Studio but running it from the TestServer gives the previous error. I tried adding references to Microsoft.AspnetCore.All directly in the test project but that did not affect anything.

**Comment by ricardo-b-dtakers** [comment]
In the meantime you can add these to your "FunctionalTests.csproj" file:

- In <PropertyGroup/>:
`<PreserveCompilationContext>true</PreserveCompilationContext>`

- As a new <Target/> element:
`  <Target Name="CopyDepsFiles" AfterTargets="Build" Condition="'$(TargetFramework)'!=''">
    <ItemGroup>
      <DepsFilePaths Include="$([System.IO.Path]::ChangeExtension('%(_ResolvedProjectReferencePaths.FullPath)', '.deps.json'))" />
    </ItemGroup>
    <Copy SourceFiles="%(DepsFilePaths.FullPath)" DestinationFolder="$(OutputPath)" Condition="Exists('%(DepsFilePaths.FullPath)')" />
  </Target>`

See https://github.com/NuGet/Home/issues/4412 for details.

**Comment by rosspace** [comment]
@ardalis Yes that worked. Thanks, @ricardo-b-dtakers!

**Comment by ardalis** [comment]
Would either of you like to send a PR to master?

**Comment by rosspace** [comment]
I'll do it.

**Comment by rosspace** [comment]
This is now resolved with the update to 2.1.
