### ISSUE TITLE
Changelog for the latest version, updated to .NET 7, is not available in the wiki page

### ISSUE THREAD

**Issue by luizen** [dotnet-architecture/eShopOnWeb#961]
In the [changelog Wiki page](https://github.com/dotnet-architecture/eShopOnWeb/wiki/Modern-Web-Apps-Azure-Developers-Changelog) the changelog for the latest version, updated to .NET 7, is missing.

It would be great to know exactly what has changed for those who read the previous version (.NET 6) and just want to catch up on the latest changes only.

**Comment by jamesmontemagno** [comment]
Hey @ardalis  do you have a full change log that we can add into a release?

**Comment by jamesmontemagno** [comment]
@SrushtiPasari94  has updated them

**Comment by ardalis** [comment]
Awesome, thanks @SrushtiPasari94 !
