### ISSUE TITLE
.NET 8 Updates

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-architecture/eShopOnWeb#963]
* [x] Update main nugets & net version
* [x] Update docker
* [x] update readme
* [x] work on release notes
* [x] make sure docker up work
* [x] make sure azd up works
* [x] make sure github actions are all working
* [x] Update documentation to mention .NET 8
* [x] Update ebook

**Comment by SrushtiPasari94** [comment]
@jamesmontemagno Expect ebook update , rest items are updated.

**Comment by jamesmontemagno** [comment]
@SrushtiPasari94  we will also need to go through each of the doc pages on https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/ and update it to say .NET 8 or ASP.NET Core 8 before creating the new eBook

**Comment by jamesmontemagno** [comment]
@SrushtiPasari94 now merged.... should update eBook and Docs

**Comment by SrushtiPasari94** [comment]
Working to update docs and generate new ebook in issue https://github.com/dotnet-architecture/eBooks/issues/255

**Comment by SrushtiPasari94** [comment]
Updated documentation and generated new ebook.
