### ISSUE TITLE
Facing issue when deploying the application on azure app service

### ISSUE THREAD

**Issue by loveleensingh97** [dotnet-architecture/eShopOnWeb#973]
Hi,

I'm encountering an internal server error while publishing my web application to Azure App Service. I need some assistance in running the eShopOnWeb Web application that has been deployed to Azure app service.

![MicrosoftTeams-image (5)](https://github.com/dotnet-architecture/eShopOnWeb/assets/43630114/0697bf89-998b-4065-b8c3-bca9e8807e8d)

**Comment by vimalgovind143** [comment]
Hello. did u manually publish the app to Azure? I suggest you delete the resource and deploy it using azd commands.
I tried recently with the latest .NET 8.0 upgrade, and it worked like a charm.  
The app is expecting the SQL connection string from secure vault could be that is the error u r facing. You can look at the logs from the log stream section.

**Comment by SrushtiPasari94** [comment]
@loveleensingh97 
You can use azd commands to deploy application on Azure App service. It works as expected . I already tested it.
For your reference : https://github.com/dotnet-architecture/eShopOnWeb?tab=readme-ov-file#running-the-sample-using-azd-template
Please reopen the issue if required.
Thanks,
Srushti
