### ISSUE TITLE
Revalidate AZD

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-architecture/eShopOnWeb#991]
Check the ports make sure things are 8080

**Comment by SrushtiPasari94** [comment]
@jamesmontemagno  Pulled the latest code --> deployed using AZD --> Did Functional testing.

![image](https://github.com/dotnet-architecture/eShopOnWeb/assets/136682990/ac11f5c9-351e-4aa8-b6e4-8db48419ae01)

![image](https://github.com/dotnet-architecture/eShopOnWeb/assets/136682990/1d5a3337-cfdd-451d-b142-c005d975894d)

![image](https://github.com/dotnet-architecture/eShopOnWeb/assets/136682990/745ac631-66bb-4bed-8043-e6a778c4d92a)

**Comment by SrushtiPasari94** [comment]
@jamesmontemagno closing the issue as testing is done and its working fine.
